### Imports

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.max_rows = 4000
pd.options.display.max_columns = 4000

# Communities Data Prep

## Clean and explore data

In [3]:
DATA_VERSION = 'v6'

In [4]:
gov_arch_csv = '../data/' + DATA_VERSION + '/Communities-Grid-view.csv'

In [5]:
gov_df = pd.read_csv(gov_arch_csv)

In [6]:
gov_df.head()

,Name,Institutions,Mechanism,Notes,Time span,Geography,Continent,Size,Source,Metanotes,Heterogeneity,FC comments,expert check,Time span: Start,Time span: End,SCCS,CORRECT TIMESPAN
0,Aedui (Celtic Oppida),"Senatus,Elected magistrates,Assemblies","Election,Council (central) ,Assembly (central)...",There are many Celtic oppida throughout northe...,2nd-1st century BC,"Europe, North",Europe,"100,001 - 1 million members","Collis, “Celtic” Oppida, in Hansen, A Comparat...",NaN,NaN,Edited March 23,NaN,-200,0,NaN,NaN
1,Akha,"Council of Elders,Village Founder-Leader (dzom...","Leader (first among equals),Gerontocracy,Blood...",see Institutions tab,20th century - Present,"Asia, Southeast",Asia,"10,001 - 100,000","Main: \nKammerer, Cornelia Ann (1985/86), Gate...",NaN,"Informal inclusion,Gender groups,Informal powe...",Edited May 23,NaN,1900,2023,NaN,NaN
2,Amalfi,"Prefetturii/ Conti/ Dogi,Sedile di congrega,Ta...","Election,Magistrate/official,Heredity,Constitu...","Camera, M, p. 29 (""La sua popolazione che nel ...",4th-12th century AD,"Europe, West",Europe,"10,001 - 100,000","Camera, M. Istoria della città e costiera di A...",NaN,NaN,Edited March 23 (could use more info on CGIs),NaN,300,1200,NaN,NaN
3,Arab nomads,"shaykh or sayyid,shura or mashwara","Consensus,Consultation,Autocratic Leader/Chief...",Nomadic Bedouin society governed by rulers sel...,"1st-7th century AD\n(start date is arbitrary, ...","Asia, Middle East",Asia,Unknown,"Stasavage, David (2020), The Decline and Rise ...",NaN,NaN,Edited Feb 23 (could use additional sources fo...,NaN,0,700,NaN,NaN
4,Assur,"King,Alum,Limmum,Scribe,City hall","President/Consul/Chief Executive,Assembly (cen...",Independent city-state. Constitutional monarch...,19th century BC\n(1920-1800 BC),"Asia, Southwest, Anatolia",Asia,"1,001 - 10,000","Larsen, M. T. The Old Assyrian City-State in H...",NaN,NaN,Edited Mar 23,Giacomo CHECKED,-1920,-1800,NaN,NaN

In [7]:
gov_df.describe()

       Time span: Start  Time span: End  CORRECT TIMESPAN
count         91.000000       91.000000               0.0
mean         847.780220     1193.615385               NaN
std         1303.354448     1162.169951               NaN
min        -4100.000000    -3300.000000               NaN
25%          650.000000     1200.000000               NaN
50%         1450.000000     1800.000000               NaN
75%         1700.000000     1900.000000               NaN
max         1900.000000     2023.000000               NaN

In [8]:
list(gov_df)

['Name',
 'Institutions',
 'Mechanism',
 'Notes',
 'Time span',
 'Geography',
 'Continent',
 'Size',
 'Source',
 'Metanotes',
 'Heterogeneity ',
 'FC comments',
 'expert check',
 'Time span: Start',
 'Time span: End',
 'SCCS',
 'CORRECT TIMESPAN']

In [9]:
gov_df.drop('CORRECT TIMESPAN', axis=1, inplace=True)

# Data prep

In [10]:
gov_df = gov_df

In [11]:
# Clean up continents
gov_df["Continent"] = gov_df["Continent"].str.strip()

In [12]:
list(gov_df['Continent'].unique())

['Europe', 'Asia', 'North America', 'Africa', 'South America', 'Oceania']

## Mechanisms

In [13]:
gov_df['Mechanism']

0     Election,Council (central) ,Assembly (central)...
1     Leader (first among equals),Gerontocracy,Blood...
2     Election,Magistrate/official,Heredity,Constitu...
3     Consensus,Consultation,Autocratic Leader/Chief...
4     President/Consul/Chief Executive,Assembly (cen...
5     Election,Plurality voting,Temporary position o...
6     Autocratic Leader/Chief (bound),Heredity,Merit...
7     Assembly (central),Checks and balances,Consent...
8     Blood relations,Tribunal/Court ,Suspension/Exp...
9     Leader (first among equals),Heredity,Matriline...
10    Magistrate/official,Consultation,Heredity,Publ...
11    Council (central) ,Gerontocracy,Matriarchy,Fem...
12    Co-optation,Temporary position of power/Term L...
13    Autocratic Leader/Chief (bound),Consultation,A...
14    Assembly (central),Confederacy,Turnover/rotati...
15    Autocratic Leader/Chief (bound),Council (centr...
16    Petition,Autocratic Leader (unbound),Divine ri...
17    Autocratic Leader/Chief (bound),Jury/Judge,Con...
18    Deliberation,Consensus,Exit,Open political uni...
19    President/Consul/Chief Executive,Council (cent...
20    President/Consul/Chief Executive,Board/Committ...
21    Assembly (central),Frequent and/or regular mee...
22    Assembly (central),Council (central) ,Magistra...
23    Matriarchy,Consensus,Council (central) ,Judici...
24    Autocratic Leader/Chief (bound),Council (centr...
25    Dreaming,Deliberation,Meritocracy,King(chief)-...
26    Assembly (central),Assembly (local),Frequent a...
27    Dual-sex political system,Matriarchy,Assembly ...
28    Assembly (central),Autocratic Leader/Chief (bo...
29    Magistrate/official,President/Consul/Chief Exe...
30    Council (central) ,Meritocracy,Property requir...
31    Autocratic Leader/Chief (bound),Board/Committe...
32    Council (central) ,Gerontocracy,Meritocracy,Pr...
33    Consensus,Election,Council (local),Lottery/Ran...
34    Autocratic Leader/Chief (bound),Checks and bal...
35    Matriarchy,Blood relations,Matrilineality,Cons...
36    Leader (first among equals),Deliberation,Corpo...
37    Council (central) ,Assembly (central),Open pol...
38    Council (central) ,Council (local),Representat...
39    Gerontocracy,Council (central) ,Frequent and/o...
40    Autocratic Leader/Chief (bound),Consent,Magist...
41    Council (local),Tribunal/Court ,Constitution,M...
42    Autocratic Leader (unbound),Council (central) ...
43    Council (central) ,Gerontocracy,Criticism/Mock...
44    Autocratic Leader/Chief (bound),Assembly (cent...
45    Matrilineality,Matriarchy,Leader (first among ...
46    Leader (first among equals),Meritocracy,Reputa...
47    Autocratic Leader (unbound),Self-help,Capital ...
48                     Assembly (local),Public meetings
49    Constitution,Election,Assembly (local),Council...
50    Leader (first among equals),Meritocracy,Electi...
51    Assembly (local),Meritocracy,Election,Delibera...
52    Leader (first among equals),Council (local),Ge...
53    Autocratic Leader/Chief (bound),Council (centr...
54    Public meetings,Meritocracy,Council (central) ...
55    Election,Blood relations,Heredity,Council (cen...
56    Temporary position of power/Term Limits,Electi...
57    Autocratic Leader/Chief (bound),Assembly (loca...
58    Election,Magistrate/official,Council (central)...
59    Autocratic Leader/Chief (bound),Council (centr...
60    Confederacy,Assembly (central),Assembly (elite...
61       Gathering,Exit,Autocratic Leader/Chief (bound)
62    Council (central) ,Meritocracy,Remunerated pos...
63    Election,Monitoring,Coalition,Magistrate/offic...
64    Council (central) ,Matriarchy,Frequent and/or ...
65    Autocratic Leader/Chief (bound),Meritocracy,Po...
66    Council (central) ,Gerontocracy,Public meeting...
67    Autocratic Leader/Chief (bound),Meritocracy,Te...
68    Autocratic Leader/Chief (bound),Induction rite...
69    Autocratic Leader/Chief (bound),Heredity,Assem...
70    Autocratic Leader/Chief (bound),Heredity,Merit...
71    King(chief)-as-Figurehead,Autocratic Leader/Ch...
72    Autocratic Leader/Chief (bound),Gerontocracy,C...
73    Council (central) ,Council (local),Gerontocrac...
74    Autocratic Leader/Chief (bound),Gerontocracy,H...
75    Gathering,Deliberation,Magistrate/official,Mer...
76    King(chief)-as-Figurehead,Heredity,Consultatio...
77    Autocratic Leader/Chief (bound),Council (local...
78    Autocratic Leader/Chief (bound),Consultation,H...
79    Council (central) ,Gerontocracy,Meritocracy,Ma...
80    Magistrate/official,Divine right,Mediation,Cou...
81    Council (central) ,Tribunal/Court ,Gerontocrac...
82    Autocratic Leader/Chief (bound),Meritocracy,Ge...
83    Magistrate/official,Autocratic Leader/Chief (b...
84    Autocratic Leader/Chief (bound),Gerontocracy,M...
85    Autocratic Leader/Chief (bound),Heredity,Merit...
86    Leader (first among equals),Popularity ,Merito...
87    Autocratic Leader/Chief (bound),Meritocracy,Li...
88    Autocratic Leader/Chief (bound),Council (local...
89    Autocratic Leader/Chief (bound),Meritocracy,Co...
90    Autocratic Leader/Chief (bound),Gerontocracy,L...
Name: Mechanism, dtype: object

In [14]:
mechanism_list = list(gov_df['Mechanism'])

In [15]:
mech_test = mechanism_list[0]

In [16]:
mech_test.split(',')

['Election',
 'Council (central) ',
 'Assembly (central)',
 'Magistrate/official',
 'Balance of power',
 'Ratification/Acclamation only']

In [17]:
test_set = set()

In [18]:
test_set.update(mech_test.split(','))
test_set

{'Assembly (central)',
 'Balance of power',
 'Council (central) ',
 'Election',
 'Magistrate/official',
 'Ratification/Acclamation only'}

In [19]:
mechanism_set = set()

In [20]:
# Create set of all mechanisms
[mechanism_set.update(mechanisms.split(',')) for mechanisms in mechanism_list]
mechanism_set

{'Age boundaries',
 'Agenda setting',
 'Alliance',
 'Appeal',
 'Arbitration',
 'Assembly (central)',
 'Assembly (elite)',
 'Assembly (local)',
 'Autocratic Leader (unbound)',
 'Autocratic Leader/Chief (bound)',
 'Balance of power',
 'Blood relations',
 'Board/Committee',
 'Bureaucracy',
 'Capital punishment',
 'Checks and balances',
 'Child participation',
 'Civil disobedience',
 'Co-optation',
 'Coalition',
 'Confederacy',
 'Consensus',
 'Consent',
 'Constitution',
 'Consultation',
 'Corporal punishment/Violence against perpetrator',
 'Council (central) ',
 'Council (local)',
 'Criticism/Mocking/Joking',
 'Delegation',
 'Deliberation',
 'Destruction of property',
 'Divine right',
 'Dreaming',
 'Dual-sex political system',
 'Election',
 'Enfranchisement',
 'Exit',
 'Female participation',
 'Fines',
 'Forced labour',
 'Frequent and/or regular meetings',
 'Gathering',
 'Gerontocracy',
 'Graduated sanctions',
 'Group voting',
 'Heredity',
 'Induction rite/ceremony',
 'Judicial review',
 'Jury/Judge',
 'King(chief)-as-Figurehead',
 'Leader (first among equals)',
 'Life appointment',
 'Litigation',
 'Lobbying',
 'Lottery/Random Selection',
 'Magistrate/official',
 'Majority voting',
 'Mandate',
 'Matriarchy',
 'Matrilineality',
 'Mediation',
 'Meritocracy',
 'Monitoring',
 'Negotiation',
 'Oath',
 'Open political unit',
 'Patronage (for office)',
 'Paying damages/compensation',
 'Payment for occupying office',
 'Petition',
 'Plurality voting',
 'Police',
 'Popularity ',
 'Power fluidity',
 'President/Consul/Chief Executive',
 'Property requirement',
 'Public meetings',
 'Quorum',
 'Ratification/Acclamation only',
 'Remunerated position',
 'Representation',
 'Reputational risk',
 'Rule of Law',
 'Screening process',
 'Scrutiny of officials',
 'Secret ballot',
 'Seizing of property',
 'Self-help',
 'Supermajority',
 'Suspension/Expulsion/Ostracism/Proscription',
 'Temporary position of power/Term Limits',
 'Tribunal/Court ',
 'Turnover/rotation',
 'Unanimity',
 'Veto',
 'Vote by proxy',
 'Vote by show of hands',
 'Voting',
 'Word of mouth'}

### Encode SCCS as true/false

In [21]:
gov_df['is_SCCS'] = gov_df['SCCS'].apply(lambda x: 1 if x == 'yes' else 0)

In [22]:
gov_df[['SCCS', 'is_SCCS']]

   SCCS  is_SCCS
0   NaN        0
1   NaN        0
2   NaN        0
3   NaN        0
4   NaN        0
5   NaN        0
6   NaN        0
7   yes        1
8   NaN        0
9   NaN        0
10  NaN        0
11  NaN        0
12  NaN        0
13  NaN        0
14  NaN        0
15  NaN        0
16  NaN        0
17  NaN        0
18  NaN        0
19  NaN        0
20  NaN        0
21  NaN        0
22  NaN        0
23  NaN        0
24  NaN        0
25  NaN        0
26  NaN        0
27  yes        1
28  NaN        0
29  NaN        0
30  NaN        0
31  NaN        0
32  NaN        0
33  NaN        0
34  NaN        0
35  NaN        0
36  yes        1
37  NaN        0
38  NaN        0
39  NaN        0
40  NaN        0
41  NaN        0
42  NaN        0
43  NaN        0
44  NaN        0
45  NaN        0
46  yes        1
47  yes        1
48  NaN        0
49  NaN        0
50  NaN        0
51  NaN        0
52  NaN        0
53  NaN        0
54  NaN        0
55  yes        1
56  yes        1
57  NaN        0
58  NaN        0
59  NaN        0
60  NaN        0
61  NaN        0
62  NaN        0
63  NaN        0
64  yes        1
65  yes        1
66  yes        1
67  yes        1
68  yes        1
69  yes        1
70  yes        1
71  yes        1
72  yes        1
73  yes        1
74  yes        1
75  yes        1
76  yes        1
77  yes        1
78  yes        1
79  yes        1
80  yes        1
81  yes        1
82  yes        1
83  yes        1
84  yes        1
85  yes        1
86  yes        1
87  yes        1
88  yes        1
89  yes        1
90  yes        1

### Add mechanism columns
Add columns in the format of `mechanism_is_{mechanism}`

In [23]:
test_df = gov_df[gov_df['Mechanism'].str.contains('Patronage (for office)', regex=False)]

In [24]:
test_df

,Name,Institutions,Mechanism,Notes,Time span,Geography,Continent,Size,Source,Metanotes,Heterogeneity,FC comments,expert check,Time span: Start,Time span: End,SCCS,is_SCCS
16,Egypt,"Pharaoh,Vizier (t3.ty),'Overseer of the Treasu...","Petition,Autocratic Leader (unbound),Divine ri...","Entry focuses on the middle kingdom, when we h...",27th-11th century BC\n\nOld Kingdom: 2700-2200...,"Africa, North",Africa,1 million - 10 million members,"'- Alexandre Alexandrovich Loktionov, Inclusiv...",NaN,NaN,Edited May 23,ALEX CHECKED,-2700,-1000,NaN,0
24,Hausa City-States,"Council of State,Sarki,Aristocratic Offices,Co...","Autocratic Leader/Chief (bound),Council (centr...","City states in Northern Nigeria, ruled by a ki...",15th to 19th century AD\n(1450-1804),"Africa, West, Nigeria",Africa,"10,001 - 100,000","Robert Griffeth, The Hausa City-States from 14...",NaN,NaN,Edited Apr 23 (perhaps find more info about th...,NaN,1450,1804,NaN,0
33,Japan (Early Modern),"Shogun,Daimyo,Village Council,Samurai,Emperor,...","Consensus,Election,Council (local),Lottery/Ran...",Corporate Landholding (warichi)\nThe distribut...,17-18th century AD,"Asia, Japan",Asia,20 million - 30 million,"Brown, Philip (2006), Arable Land as Commons: ...","There were around 27 provinces, controlled by ...","Social groups,Inclusion through different inst...",Edited May 23 (can use more information abut t...,NaN,1600,1800,NaN,0

In [25]:
gov_df['Mechanism']

0     Election,Council (central) ,Assembly (central)...
1     Leader (first among equals),Gerontocracy,Blood...
2     Election,Magistrate/official,Heredity,Constitu...
3     Consensus,Consultation,Autocratic Leader/Chief...
4     President/Consul/Chief Executive,Assembly (cen...
5     Election,Plurality voting,Temporary position o...
6     Autocratic Leader/Chief (bound),Heredity,Merit...
7     Assembly (central),Checks and balances,Consent...
8     Blood relations,Tribunal/Court ,Suspension/Exp...
9     Leader (first among equals),Heredity,Matriline...
10    Magistrate/official,Consultation,Heredity,Publ...
11    Council (central) ,Gerontocracy,Matriarchy,Fem...
12    Co-optation,Temporary position of power/Term L...
13    Autocratic Leader/Chief (bound),Consultation,A...
14    Assembly (central),Confederacy,Turnover/rotati...
15    Autocratic Leader/Chief (bound),Council (centr...
16    Petition,Autocratic Leader (unbound),Divine ri...
17    Autocratic Leader/Chief (bound),Jury/Judge,Con...
18    Deliberation,Consensus,Exit,Open political uni...
19    President/Consul/Chief Executive,Council (cent...
20    President/Consul/Chief Executive,Board/Committ...
21    Assembly (central),Frequent and/or regular mee...
22    Assembly (central),Council (central) ,Magistra...
23    Matriarchy,Consensus,Council (central) ,Judici...
24    Autocratic Leader/Chief (bound),Council (centr...
25    Dreaming,Deliberation,Meritocracy,King(chief)-...
26    Assembly (central),Assembly (local),Frequent a...
27    Dual-sex political system,Matriarchy,Assembly ...
28    Assembly (central),Autocratic Leader/Chief (bo...
29    Magistrate/official,President/Consul/Chief Exe...
30    Council (central) ,Meritocracy,Property requir...
31    Autocratic Leader/Chief (bound),Board/Committe...
32    Council (central) ,Gerontocracy,Meritocracy,Pr...
33    Consensus,Election,Council (local),Lottery/Ran...
34    Autocratic Leader/Chief (bound),Checks and bal...
35    Matriarchy,Blood relations,Matrilineality,Cons...
36    Leader (first among equals),Deliberation,Corpo...
37    Council (central) ,Assembly (central),Open pol...
38    Council (central) ,Council (local),Representat...
39    Gerontocracy,Council (central) ,Frequent and/o...
40    Autocratic Leader/Chief (bound),Consent,Magist...
41    Council (local),Tribunal/Court ,Constitution,M...
42    Autocratic Leader (unbound),Council (central) ...
43    Council (central) ,Gerontocracy,Criticism/Mock...
44    Autocratic Leader/Chief (bound),Assembly (cent...
45    Matrilineality,Matriarchy,Leader (first among ...
46    Leader (first among equals),Meritocracy,Reputa...
47    Autocratic Leader (unbound),Self-help,Capital ...
48                     Assembly (local),Public meetings
49    Constitution,Election,Assembly (local),Council...
50    Leader (first among equals),Meritocracy,Electi...
51    Assembly (local),Meritocracy,Election,Delibera...
52    Leader (first among equals),Council (local),Ge...
53    Autocratic Leader/Chief (bound),Council (centr...
54    Public meetings,Meritocracy,Council (central) ...
55    Election,Blood relations,Heredity,Council (cen...
56    Temporary position of power/Term Limits,Electi...
57    Autocratic Leader/Chief (bound),Assembly (loca...
58    Election,Magistrate/official,Council (central)...
59    Autocratic Leader/Chief (bound),Council (centr...
60    Confederacy,Assembly (central),Assembly (elite...
61       Gathering,Exit,Autocratic Leader/Chief (bound)
62    Council (central) ,Meritocracy,Remunerated pos...
63    Election,Monitoring,Coalition,Magistrate/offic...
64    Council (central) ,Matriarchy,Frequent and/or ...
65    Autocratic Leader/Chief (bound),Meritocracy,Po...
66    Council (central) ,Gerontocracy,Public meeting...
67    Autocratic Leader/Chief (bound),Meritocracy,Te...
68    Autocratic Leader/Chief (bound),Induction rite...
69    Autocratic Leader/Chief (bound),Heredity,Assem...
70    Autocratic Leader/Chief (bound),Heredity,Merit...
71    King(chief)-as-Figurehead,Autocratic Leader/Ch...
72    Autocratic Leader/Chief (bound),Gerontocracy,C...
73    Council (central) ,Council (local),Gerontocrac...
74    Autocratic Leader/Chief (bound),Gerontocracy,H...
75    Gathering,Deliberation,Magistrate/official,Mer...
76    King(chief)-as-Figurehead,Heredity,Consultatio...
77    Autocratic Leader/Chief (bound),Council (local...
78    Autocratic Leader/Chief (bound),Consultation,H...
79    Council (central) ,Gerontocracy,Meritocracy,Ma...
80    Magistrate/official,Divine right,Mediation,Cou...
81    Council (central) ,Tribunal/Court ,Gerontocrac...
82    Autocratic Leader/Chief (bound),Meritocracy,Ge...
83    Magistrate/official,Autocratic Leader/Chief (b...
84    Autocratic Leader/Chief (bound),Gerontocracy,M...
85    Autocratic Leader/Chief (bound),Heredity,Merit...
86    Leader (first among equals),Popularity ,Merito...
87    Autocratic Leader/Chief (bound),Meritocracy,Li...
88    Autocratic Leader/Chief (bound),Council (local...
89    Autocratic Leader/Chief (bound),Meritocracy,Co...
90    Autocratic Leader/Chief (bound),Gerontocracy,L...
Name: Mechanism, dtype: object

In [26]:
mechanism_set

{'Age boundaries',
 'Agenda setting',
 'Alliance',
 'Appeal',
 'Arbitration',
 'Assembly (central)',
 'Assembly (elite)',
 'Assembly (local)',
 'Autocratic Leader (unbound)',
 'Autocratic Leader/Chief (bound)',
 'Balance of power',
 'Blood relations',
 'Board/Committee',
 'Bureaucracy',
 'Capital punishment',
 'Checks and balances',
 'Child participation',
 'Civil disobedience',
 'Co-optation',
 'Coalition',
 'Confederacy',
 'Consensus',
 'Consent',
 'Constitution',
 'Consultation',
 'Corporal punishment/Violence against perpetrator',
 'Council (central) ',
 'Council (local)',
 'Criticism/Mocking/Joking',
 'Delegation',
 'Deliberation',
 'Destruction of property',
 'Divine right',
 'Dreaming',
 'Dual-sex political system',
 'Election',
 'Enfranchisement',
 'Exit',
 'Female participation',
 'Fines',
 'Forced labour',
 'Frequent and/or regular meetings',
 'Gathering',
 'Gerontocracy',
 'Graduated sanctions',
 'Group voting',
 'Heredity',
 'Induction rite/ceremony',
 'Judicial review',
 'Jury/Judge',
 'King(chief)-as-Figurehead',
 'Leader (first among equals)',
 'Life appointment',
 'Litigation',
 'Lobbying',
 'Lottery/Random Selection',
 'Magistrate/official',
 'Majority voting',
 'Mandate',
 'Matriarchy',
 'Matrilineality',
 'Mediation',
 'Meritocracy',
 'Monitoring',
 'Negotiation',
 'Oath',
 'Open political unit',
 'Patronage (for office)',
 'Paying damages/compensation',
 'Payment for occupying office',
 'Petition',
 'Plurality voting',
 'Police',
 'Popularity ',
 'Power fluidity',
 'President/Consul/Chief Executive',
 'Property requirement',
 'Public meetings',
 'Quorum',
 'Ratification/Acclamation only',
 'Remunerated position',
 'Representation',
 'Reputational risk',
 'Rule of Law',
 'Screening process',
 'Scrutiny of officials',
 'Secret ballot',
 'Seizing of property',
 'Self-help',
 'Supermajority',
 'Suspension/Expulsion/Ostracism/Proscription',
 'Temporary position of power/Term Limits',
 'Tribunal/Court ',
 'Turnover/rotation',
 'Unanimity',
 'Veto',
 'Vote by proxy',
 'Vote by show of hands',
 'Voting',
 'Word of mouth'}

### Categorize Mechanisms by: Access, Decision Making, Enforcement

In [27]:
access = [
 'mechanisms_include_meritocracy',
 'mechanisms_include_age_boundaries',
 'mechanisms_include_blood_relations',
 'mechanisms_include_life_appointment',
 'mechanisms_include_co-optation',
 'mechanisms_include_patronage_for_office',
 'mechanisms_include_heredity',
 'mechanisms_include_lottery_random_selection',
 'mechanisms_include_matriarchy',
 'mechanisms_include_screening_process',
 'mechanisms_include_property_requirement',
 'mechanisms_include_induction_rite_ceremony',
 'mechanisms_include_matrilineality',
 'mechanisms_include_enfranchisement',
 'mechanisms_include_popularity_',
 'mechanisms_include_divine_right',
 'mechanisms_include_payment_for_occupying_office',
 'mechanisms_include_gerontocracy',
 'mechanisms_include_open_political_unit',
 'mechanisms_include_election',
 'mechanisms_include_dreaming',
 'mechanisms_include_female_participation',
 'mechanisms_include_child_participation'
]

decision_making = [
 'mechanisms_include_secret_ballot',
 'mechanisms_include_vote_by_proxy',
 'mechanisms_include_voting',
 'mechanisms_include_mandate',
 'mechanisms_include_lobbying',
 'mechanisms_include_representation',
 'mechanisms_include_consensus',
 'mechanisms_include_magistrate_official',
 'mechanisms_include_word_of_mouth',
 'mechanisms_include_consultation',
 'mechanisms_include_checks_and_balances',
 'mechanisms_include_council_central_',
 'mechanisms_include_unanimity',
 'mechanisms_include_kingchief-as-figurehead',
 'mechanisms_include_deliberation',
 'mechanisms_include_autocratic_leader_chief_bound',
 'mechanisms_include_plurality_voting',
 'mechanisms_include_leader_first_among_equals',
 'mechanisms_include_power_fluidity',
 'mechanisms_include_petition',
 'mechanisms_include_delegation',
 'mechanisms_include_vote_by_show_of_hands',
 'mechanisms_include_temporary_position_of_power_term_limits',
 'mechanisms_include_ratification_acclamation_only',
 'mechanisms_include_rule_of_law',
 'mechanisms_include_assembly_central',
 'mechanisms_include_supermajority',
 'mechanisms_include_handshake',
 'mechanisms_include_bureaucracy',
 'mechanisms_include_majority_voting',
 'mechanisms_include_alliance',
 'mechanisms_include_board_committee',
 'mechanisms_include_dual-sex_political_system',
 'mechanisms_include_remunerated_position',
 'mechanisms_include_public_meetings',
 'mechanisms_include_balance_of_power',
 'mechanisms_include_consent',
 'mechanisms_include_turnover_rotation',
 'mechanisms_include_quorum',
 'mechanisms_include_frequent_and_or_regular_meetings',
 'mechanisms_include_confederacy',
 'mechanisms_include_assembly_local',
 'mechanisms_include_council_local',
 'mechanisms_include_oath',
 'mechanisms_include_constitution',
 'mechanisms_include_president_consul_chief_executive',
 'mechanisms_include_veto',
 'mechanisms_include_autocratic_leader_unbound',
 'mechanisms_include_assembly_elite',
 'mechanisms_include_agenda_setting',
 'mechanisms_include_group_voting',
 'mechanisms_include_coalition',
 'mechanisms_include_gathering'
]

enforcement = [
 'mechanisms_include_negotiation',
 'mechanisms_include_suspension_expulsion_ostracism_proscription',
 'mechanisms_include_fines',
 'mechanisms_include_criticism_mocking_joking',
 'mechanisms_include_corporal_punishment_violence_against_perpetrator',
 'mechanisms_include_forced_labour',
 'mechanisms_include_paying_damages_compensation',
 'mechanisms_include_seizing_of_property',
 'mechanisms_include_monitoring',
 'mechanisms_include_reputational_risk',
 'mechanisms_include_appeal',
 'mechanisms_include_graduated_sanctions',
 'mechanisms_include_self-help',
 'mechanisms_include_civil_disobedience',
 'mechanisms_include_military_force',
 'mechanisms_include_arbitration',
 'mechanisms_include_police',
 'mechanisms_include_exit',
 'mechanisms_include_jury_judge',
 'mechanisms_include_capital_punishment',
 'mechanisms_include_mediation',
 'mechanisms_include_destruction_of_property',
 'mechanisms_include_litigation',
 'mechanisms_include_tribunal_court_',
 'mechanisms_include_judicial_review',
 'mechanisms_include_scrutiny_of_officials'
]

In [28]:
def categorize_mechanism(mechanism):
    if mechanism in access:
        return 'access_'
    elif mechanism in decision_making:
        return 'decision_making_'
    elif mechanism in enforcement:
        return 'enforcement_'

    return ''

In [29]:
for mechanism in mechanism_set:
    mechanism_str = mechanism.lower().replace(' ', '_').replace('/', '_').replace('(','').replace(')','') # Normalize text
    mechanism_name = 'mechanisms_include_' + mechanism_str
    col_name = categorize_mechanism(mechanism_name) + mechanism_name
    
    gov_df[col_name] = np.where(gov_df['Mechanism'].str.contains(mechanism, regex=False), 1, 0)

/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/776440318.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Mechanism'].str.contains(mechanism, regex=False), 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/776440318.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Mechanism'].str.contains(mechanism, regex=False), 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/776440318.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Mechanism'].str.contains(mechanism, regex=False), 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/776440318.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Mechanism'].str.contains(mechanism, regex=False), 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/776440318.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Mechanism'].str.contains(mechanism, regex=False), 1, 0)

In [30]:
list(gov_df.columns)

['Name',
 'Institutions',
 'Mechanism',
 'Notes',
 'Time span',
 'Geography',
 'Continent',
 'Size',
 'Source',
 'Metanotes',
 'Heterogeneity ',
 'FC comments',
 'expert check',
 'Time span: Start',
 'Time span: End',
 'SCCS',
 'is_SCCS',
 'enforcement_mechanisms_include_tribunal_court_',
 'decision_making_mechanisms_include_checks_and_balances',
 'decision_making_mechanisms_include_rule_of_law',
 'enforcement_mechanisms_include_reputational_risk',
 'decision_making_mechanisms_include_confederacy',
 'decision_making_mechanisms_include_consultation',
 'decision_making_mechanisms_include_power_fluidity',
 'enforcement_mechanisms_include_police',
 'decision_making_mechanisms_include_coalition',
 'enforcement_mechanisms_include_fines',
 'decision_making_mechanisms_include_veto',
 'decision_making_mechanisms_include_majority_voting',
 'enforcement_mechanisms_include_jury_judge',
 'decision_making_mechanisms_include_mandate',
 'enforcement_mechanisms_include_paying_damages_compensation',
 'decision_making_mechanisms_include_bureaucracy',
 'decision_making_mechanisms_include_word_of_mouth',
 'decision_making_mechanisms_include_assembly_local',
 'decision_making_mechanisms_include_dual-sex_political_system',
 'enforcement_mechanisms_include_civil_disobedience',
 'decision_making_mechanisms_include_assembly_elite',
 'access_mechanisms_include_enfranchisement',
 'decision_making_mechanisms_include_alliance',
 'decision_making_mechanisms_include_kingchief-as-figurehead',
 'decision_making_mechanisms_include_group_voting',
 'decision_making_mechanisms_include_plurality_voting',
 'decision_making_mechanisms_include_vote_by_show_of_hands',
 'decision_making_mechanisms_include_delegation',
 'decision_making_mechanisms_include_board_committee',
 'access_mechanisms_include_screening_process',
 'access_mechanisms_include_divine_right',
 'enforcement_mechanisms_include_negotiation',
 'decision_making_mechanisms_include_magistrate_official',
 'decision_making_mechanisms_include_council_local',
 'enforcement_mechanisms_include_mediation',
 'decision_making_mechanisms_include_lobbying',
 'enforcement_mechanisms_include_capital_punishment',
 'access_mechanisms_include_lottery_random_selection',
 'enforcement_mechanisms_include_graduated_sanctions',
 'decision_making_mechanisms_include_frequent_and_or_regular_meetings',
 'decision_making_mechanisms_include_gathering',
 'access_mechanisms_include_dreaming',
 'enforcement_mechanisms_include_criticism_mocking_joking',
 'access_mechanisms_include_meritocracy',
 'decision_making_mechanisms_include_agenda_setting',
 'access_mechanisms_include_matriarchy',
 'access_mechanisms_include_payment_for_occupying_office',
 'access_mechanisms_include_child_participation',
 'decision_making_mechanisms_include_secret_ballot',
 'access_mechanisms_include_gerontocracy',
 'decision_making_mechanisms_include_temporary_position_of_power_term_limits',
 'enforcement_mechanisms_include_destruction_of_property',
 'access_mechanisms_include_patronage_for_office',
 'decision_making_mechanisms_include_turnover_rotation',
 'access_mechanisms_include_heredity',
 'decision_making_mechanisms_include_autocratic_leader_chief_bound',
 'decision_making_mechanisms_include_assembly_central',
 'enforcement_mechanisms_include_self-help',
 'decision_making_mechanisms_include_petition',
 'enforcement_mechanisms_include_suspension_expulsion_ostracism_proscription',
 'access_mechanisms_include_blood_relations',
 'enforcement_mechanisms_include_monitoring',
 'enforcement_mechanisms_include_corporal_punishment_violence_against_perpetrator',
 'decision_making_mechanisms_include_balance_of_power',
 'decision_making_mechanisms_include_council_central_',
 'access_mechanisms_include_female_participation',
 'decision_making_mechanisms_include_deliberation',
 'enforcement_mechanisms_include_exit',
 'enforcement_mechanisms_include_appeal',
 'access_mechanisms_include_popularity_',
 'decision_making_mechanisms_include_unanimity',
 'enforcement_mechanisms_include_judicial_review',
 'decision_making_mechanisms_include_oath',
 'decision_making_mechanisms_include_supermajority',
 'enforcement_mechanisms_include_seizing_of_property',
 'enforcement_mechanisms_include_arbitration',
 'decision_making_mechanisms_include_remunerated_position',
 'enforcement_mechanisms_include_litigation',
 'decision_making_mechanisms_include_representation',
 'decision_making_mechanisms_include_quorum',
 'decision_making_mechanisms_include_consent',
 'access_mechanisms_include_co-optation',
 'decision_making_mechanisms_include_constitution',
 'access_mechanisms_include_induction_rite_ceremony',
 'enforcement_mechanisms_include_scrutiny_of_officials',
 'decision_making_mechanisms_include_president_consul_chief_executive',
 'decision_making_mechanisms_include_public_meetings',
 'access_mechanisms_include_age_boundaries',
 'decision_making_mechanisms_include_vote_by_proxy',
 'decision_making_mechanisms_include_voting',
 'access_mechanisms_include_matrilineality',
 'decision_making_mechanisms_include_consensus',
 'decision_making_mechanisms_include_ratification_acclamation_only',
 'access_mechanisms_include_election',
 'access_mechanisms_include_life_appointment',
 'access_mechanisms_include_property_requirement',
 'decision_making_mechanisms_include_autocratic_leader_unbound',
 'access_mechanisms_include_open_political_unit',
 'enforcement_mechanisms_include_forced_labour',
 'decision_making_mechanisms_include_leader_first_among_equals']

In [31]:
mechanisms = [mechanism for mechanism in list(gov_df.columns) if 'mechanisms_include' in mechanism]

In [32]:
access_mechanisms = [mechanism for mechanism in list(gov_df.columns) if 'access_' in mechanism]

In [33]:
decision_making_mechanisms = [mechanism for mechanism in list(gov_df.columns) if 'decision_making_' in mechanism]

In [34]:
enforcement_mechanisms = [mechanism for mechanism in list(gov_df.columns) if 'enforcement_' in mechanism]

In [35]:
sorted(mechanisms)

['access_mechanisms_include_age_boundaries',
 'access_mechanisms_include_blood_relations',
 'access_mechanisms_include_child_participation',
 'access_mechanisms_include_co-optation',
 'access_mechanisms_include_divine_right',
 'access_mechanisms_include_dreaming',
 'access_mechanisms_include_election',
 'access_mechanisms_include_enfranchisement',
 'access_mechanisms_include_female_participation',
 'access_mechanisms_include_gerontocracy',
 'access_mechanisms_include_heredity',
 'access_mechanisms_include_induction_rite_ceremony',
 'access_mechanisms_include_life_appointment',
 'access_mechanisms_include_lottery_random_selection',
 'access_mechanisms_include_matriarchy',
 'access_mechanisms_include_matrilineality',
 'access_mechanisms_include_meritocracy',
 'access_mechanisms_include_open_political_unit',
 'access_mechanisms_include_patronage_for_office',
 'access_mechanisms_include_payment_for_occupying_office',
 'access_mechanisms_include_popularity_',
 'access_mechanisms_include_property_requirement',
 'access_mechanisms_include_screening_process',
 'decision_making_mechanisms_include_agenda_setting',
 'decision_making_mechanisms_include_alliance',
 'decision_making_mechanisms_include_assembly_central',
 'decision_making_mechanisms_include_assembly_elite',
 'decision_making_mechanisms_include_assembly_local',
 'decision_making_mechanisms_include_autocratic_leader_chief_bound',
 'decision_making_mechanisms_include_autocratic_leader_unbound',
 'decision_making_mechanisms_include_balance_of_power',
 'decision_making_mechanisms_include_board_committee',
 'decision_making_mechanisms_include_bureaucracy',
 'decision_making_mechanisms_include_checks_and_balances',
 'decision_making_mechanisms_include_coalition',
 'decision_making_mechanisms_include_confederacy',
 'decision_making_mechanisms_include_consensus',
 'decision_making_mechanisms_include_consent',
 'decision_making_mechanisms_include_constitution',
 'decision_making_mechanisms_include_consultation',
 'decision_making_mechanisms_include_council_central_',
 'decision_making_mechanisms_include_council_local',
 'decision_making_mechanisms_include_delegation',
 'decision_making_mechanisms_include_deliberation',
 'decision_making_mechanisms_include_dual-sex_political_system',
 'decision_making_mechanisms_include_frequent_and_or_regular_meetings',
 'decision_making_mechanisms_include_gathering',
 'decision_making_mechanisms_include_group_voting',
 'decision_making_mechanisms_include_kingchief-as-figurehead',
 'decision_making_mechanisms_include_leader_first_among_equals',
 'decision_making_mechanisms_include_lobbying',
 'decision_making_mechanisms_include_magistrate_official',
 'decision_making_mechanisms_include_majority_voting',
 'decision_making_mechanisms_include_mandate',
 'decision_making_mechanisms_include_oath',
 'decision_making_mechanisms_include_petition',
 'decision_making_mechanisms_include_plurality_voting',
 'decision_making_mechanisms_include_power_fluidity',
 'decision_making_mechanisms_include_president_consul_chief_executive',
 'decision_making_mechanisms_include_public_meetings',
 'decision_making_mechanisms_include_quorum',
 'decision_making_mechanisms_include_ratification_acclamation_only',
 'decision_making_mechanisms_include_remunerated_position',
 'decision_making_mechanisms_include_representation',
 'decision_making_mechanisms_include_rule_of_law',
 'decision_making_mechanisms_include_secret_ballot',
 'decision_making_mechanisms_include_supermajority',
 'decision_making_mechanisms_include_temporary_position_of_power_term_limits',
 'decision_making_mechanisms_include_turnover_rotation',
 'decision_making_mechanisms_include_unanimity',
 'decision_making_mechanisms_include_veto',
 'decision_making_mechanisms_include_vote_by_proxy',
 'decision_making_mechanisms_include_vote_by_show_of_hands',
 'decision_making_mechanisms_include_voting',
 'decision_making_mechanisms_include_word_of_mouth',
 'enforcement_mechanisms_include_appeal',
 'enforcement_mechanisms_include_arbitration',
 'enforcement_mechanisms_include_capital_punishment',
 'enforcement_mechanisms_include_civil_disobedience',
 'enforcement_mechanisms_include_corporal_punishment_violence_against_perpetrator',
 'enforcement_mechanisms_include_criticism_mocking_joking',
 'enforcement_mechanisms_include_destruction_of_property',
 'enforcement_mechanisms_include_exit',
 'enforcement_mechanisms_include_fines',
 'enforcement_mechanisms_include_forced_labour',
 'enforcement_mechanisms_include_graduated_sanctions',
 'enforcement_mechanisms_include_judicial_review',
 'enforcement_mechanisms_include_jury_judge',
 'enforcement_mechanisms_include_litigation',
 'enforcement_mechanisms_include_mediation',
 'enforcement_mechanisms_include_monitoring',
 'enforcement_mechanisms_include_negotiation',
 'enforcement_mechanisms_include_paying_damages_compensation',
 'enforcement_mechanisms_include_police',
 'enforcement_mechanisms_include_reputational_risk',
 'enforcement_mechanisms_include_scrutiny_of_officials',
 'enforcement_mechanisms_include_seizing_of_property',
 'enforcement_mechanisms_include_self-help',
 'enforcement_mechanisms_include_suspension_expulsion_ostracism_proscription',
 'enforcement_mechanisms_include_tribunal_court_']

In [36]:
len(mechanisms)

100

In [37]:
len(access_mechanisms) + len(decision_making_mechanisms) + len(enforcement_mechanisms)

100

In [38]:
access_mechanisms

['access_mechanisms_include_enfranchisement',
 'access_mechanisms_include_screening_process',
 'access_mechanisms_include_divine_right',
 'access_mechanisms_include_lottery_random_selection',
 'access_mechanisms_include_dreaming',
 'access_mechanisms_include_meritocracy',
 'access_mechanisms_include_matriarchy',
 'access_mechanisms_include_payment_for_occupying_office',
 'access_mechanisms_include_child_participation',
 'access_mechanisms_include_gerontocracy',
 'access_mechanisms_include_patronage_for_office',
 'access_mechanisms_include_heredity',
 'access_mechanisms_include_blood_relations',
 'access_mechanisms_include_female_participation',
 'access_mechanisms_include_popularity_',
 'access_mechanisms_include_co-optation',
 'access_mechanisms_include_induction_rite_ceremony',
 'access_mechanisms_include_age_boundaries',
 'access_mechanisms_include_matrilineality',
 'access_mechanisms_include_election',
 'access_mechanisms_include_life_appointment',
 'access_mechanisms_include_property_requirement',
 'access_mechanisms_include_open_political_unit']

In [39]:
len(mechanisms)

100

In [40]:
gov_df[mechanisms].sum().sort_values(ascending=True)

decision_making_mechanisms_include_lobbying                                         1
decision_making_mechanisms_include_power_fluidity                                   1
enforcement_mechanisms_include_civil_disobedience                                   1
decision_making_mechanisms_include_coalition                                        1
decision_making_mechanisms_include_petition                                         1
decision_making_mechanisms_include_group_voting                                     1
decision_making_mechanisms_include_mandate                                          1
access_mechanisms_include_enfranchisement                                           2
enforcement_mechanisms_include_destruction_of_property                              2
decision_making_mechanisms_include_supermajority                                    2
access_mechanisms_include_screening_process                                         2
decision_making_mechanisms_include_oath                                             2
decision_making_mechanisms_include_quorum                                           2
decision_making_mechanisms_include_word_of_mouth                                    2
decision_making_mechanisms_include_bureaucracy                                      2
decision_making_mechanisms_include_vote_by_proxy                                    2
enforcement_mechanisms_include_judicial_review                                      2
enforcement_mechanisms_include_monitoring                                           2
enforcement_mechanisms_include_graduated_sanctions                                  2
decision_making_mechanisms_include_rule_of_law                                      2
enforcement_mechanisms_include_forced_labour                                        2
decision_making_mechanisms_include_plurality_voting                                 2
decision_making_mechanisms_include_secret_ballot                                    3
enforcement_mechanisms_include_negotiation                                          3
access_mechanisms_include_payment_for_occupying_office                              3
access_mechanisms_include_dreaming                                                  3
enforcement_mechanisms_include_seizing_of_property                                  3
access_mechanisms_include_patronage_for_office                                      3
decision_making_mechanisms_include_turnover_rotation                                3
enforcement_mechanisms_include_scrutiny_of_officials                                3
enforcement_mechanisms_include_paying_damages_compensation                          3
access_mechanisms_include_co-optation                                               3
enforcement_mechanisms_include_appeal                                               3
decision_making_mechanisms_include_vote_by_show_of_hands                            3
enforcement_mechanisms_include_reputational_risk                                    4
enforcement_mechanisms_include_litigation                                           4
access_mechanisms_include_lottery_random_selection                                  4
decision_making_mechanisms_include_balance_of_power                                 4
decision_making_mechanisms_include_veto                                             4
decision_making_mechanisms_include_dual-sex_political_system                        4
access_mechanisms_include_divine_right                                              4
decision_making_mechanisms_include_agenda_setting                                   4
access_mechanisms_include_child_participation                                       4
enforcement_mechanisms_include_exit                                                 4
access_mechanisms_include_property_requirement                                      5
decision_making_mechanisms_include_autocratic_leader_unbound                        5
access_mechanisms_include_induction_rite_ceremony                                   5
decision_making_mechanisms_include_alliance                                         5
enforcement_mechanisms_include_fines                                                5
enforcement_mechanisms_include_capital_punishment                                   6
access_mechanisms_include_open_political_unit                                       6
decision_making_mechanisms_include_ratification_acclamation_only                    6
enforcement_mechanisms_include_criticism_mocking_joking                             6
enforcement_mechanisms_include_self-help                                            6
access_mechanisms_include_popularity_                                               7
decision_making_mechanisms_include_constitution                                     7
decision_making_mechanisms_include_unanimity                                        7
enforcement_mechanisms_include_police                                               7
access_mechanisms_include_matriarchy                                                7
access_mechanisms_include_age_boundaries                                            7
enforcement_mechanisms_include_suspension_expulsion_ostracism_proscription          8
decision_making_mechanisms_include_assembly_elite                                   8
decision_making_mechanisms_include_delegation                                       8
decision_making_mechanisms_include_board_committee                                  8
enforcement_mechanisms_include_mediation                                            8
decision_making_mechanisms_include_majority_voting                                  8
access_mechanisms_include_matrilineality                                            8
enforcement_mechanisms_include_arbitration                                          9
decision_making_mechanisms_include_leader_first_among_equals                        9
decision_making_mechanisms_include_voting                                           9
decision_making_mechanisms_include_checks_and_balances                              9
decision_making_mechanisms_include_confederacy                                      9
enforcement_mechanisms_include_corporal_punishment_violence_against_perpetrator    10
access_mechanisms_include_life_appointment                                         10
decision_making_mechanisms_include_remunerated_position                            10
decision_making_mechanisms_include_kingchief-as-figurehead                         10
decision_making_mechanisms_include_consent                                         10
enforcement_mechanisms_include_jury_judge                                          10
decision_making_mechanisms_include_president_consul_chief_executive                12
decision_making_mechanisms_include_gathering                                       12
decision_making_mechanisms_include_assembly_local                                  13
access_mechanisms_include_blood_relations                                          14
decision_making_mechanisms_include_consultation                                    16
decision_making_mechanisms_include_frequent_and_or_regular_meetings                18
decision_making_mechanisms_include_public_meetings                                 18
decision_making_mechanisms_include_temporary_position_of_power_term_limits         21
access_mechanisms_include_female_participation                                     22
enforcement_mechanisms_include_tribunal_court_                                     23
decision_making_mechanisms_include_representation                                  24
decision_making_mechanisms_include_consensus                                       25
decision_making_mechanisms_include_assembly_central                                27
access_mechanisms_include_election                                                 28
decision_making_mechanisms_include_council_local                                   28
decision_making_mechanisms_include_deliberation                                    34
access_mechanisms_include_gerontocracy                                             36
decision_making_mechanisms_include_autocratic_leader_chief_bound                   38
access_mechanisms_include_heredity                                                 40
access_mechanisms_include_meritocracy                                              40
decision_making_mechanisms_include_council_central_                                53
decision_making_mechanisms_include_magistrate_official                             61
dtype: int64

In [41]:
gov_df[mechanisms].head()

,enforcement_mechanisms_include_tribunal_court_,decision_making_mechanisms_include_checks_and_balances,decision_making_mechanisms_include_rule_of_law,enforcement_mechanisms_include_reputational_risk,decision_making_mechanisms_include_confederacy,decision_making_mechanisms_include_consultation,decision_making_mechanisms_include_power_fluidity,enforcement_mechanisms_include_police,decision_making_mechanisms_include_coalition,enforcement_mechanisms_include_fines,decision_making_mechanisms_include_veto,decision_making_mechanisms_include_majority_voting,enforcement_mechanisms_include_jury_judge,decision_making_mechanisms_include_mandate,enforcement_mechanisms_include_paying_damages_compensation,decision_making_mechanisms_include_bureaucracy,decision_making_mechanisms_include_word_of_mouth,decision_making_mechanisms_include_assembly_local,decision_making_mechanisms_include_dual-sex_political_system,enforcement_mechanisms_include_civil_disobedience,decision_making_mechanisms_include_assembly_elite,access_mechanisms_include_enfranchisement,decision_making_mechanisms_include_alliance,decision_making_mechanisms_include_kingchief-as-figurehead,decision_making_mechanisms_include_group_voting,decision_making_mechanisms_include_plurality_voting,decision_making_mechanisms_include_vote_by_show_of_hands,decision_making_mechanisms_include_delegation,decision_making_mechanisms_include_board_committee,access_mechanisms_include_screening_process,access_mechanisms_include_divine_right,enforcement_mechanisms_include_negotiation,decision_making_mechanisms_include_magistrate_official,decision_making_mechanisms_include_council_local,enforcement_mechanisms_include_mediation,decision_making_mechanisms_include_lobbying,enforcement_mechanisms_include_capital_punishment,access_mechanisms_include_lottery_random_selection,enforcement_mechanisms_include_graduated_sanctions,decision_making_mechanisms_include_frequent_and_or_regular_meetings,decision_making_mechanisms_include_gathering,access_mechanisms_include_dreaming,enforcement_mechanisms_include_criticism_mocking_joking,access_mechanisms_include_meritocracy,decision_making_mechanisms_include_agenda_setting,access_mechanisms_include_matriarchy,access_mechanisms_include_payment_for_occupying_office,access_mechanisms_include_child_participation,decision_making_mechanisms_include_secret_ballot,access_mechanisms_include_gerontocracy,decision_making_mechanisms_include_temporary_position_of_power_term_limits,enforcement_mechanisms_include_destruction_of_property,access_mechanisms_include_patronage_for_office,decision_making_mechanisms_include_turnover_rotation,access_mechanisms_include_heredity,decision_making_mechanisms_include_autocratic_leader_chief_bound,decision_making_mechanisms_include_assembly_central,enforcement_mechanisms_include_self-help,decision_making_mechanisms_include_petition,enforcement_mechanisms_include_suspension_expulsion_ostracism_proscription,access_mechanisms_include_blood_relations,enforcement_mechanisms_include_monitoring,enforcement_mechanisms_include_corporal_punishment_violence_against_perpetrator,decision_making_mechanisms_include_balance_of_power,decision_making_mechanisms_include_council_central_,access_mechanisms_include_female_participation,decision_making_mechanisms_include_deliberation,enforcement_mechanisms_include_exit,enforcement_mechanisms_include_appeal,access_mechanisms_include_popularity_,decision_making_mechanisms_include_unanimity,enforcement_mechanisms_include_judicial_review,decision_making_mechanisms_include_oath,decision_making_mechanisms_include_supermajority,enforcement_mechanisms_include_seizing_of_property,enforcement_mechanisms_include_arbitration,decision_making_mechanisms_include_remunerated_position,enforcement_mechanisms_include_litigation,decision_making_mechanisms_include_representation,decision_making_mechanisms_include_quorum,decision_making_mechanisms_include_consent,access_mechanisms_include_co-optation,decision_making_mechanisms_include_constitution,access_mechanisms_include_induction_rite_ceremony,enforcement_mechanisms_include_scrutiny_of_officials,decision_making_mechanisms_include_president_consul_chief_executive,decision_making_mechanisms_include_public_meetings,access_mechanisms_include_age_boundaries,decision_making_mechanisms_include_vote_by_proxy,decision_making_mechanisms_include_voting,access_mechanisms_include_matrilineality,decision_making_mechanisms_include_consensus,decision_making_mechanisms_include_ratification_acclamation_only,access_mechanisms_include_election,access_mechanisms_include_life_appointment,access_mechanisms_include_property_requirement,decision_making_mechanisms_include_autocratic_leader_unbound,access_mechanisms_include_open_political_unit,enforcement_mechanisms_include_forced_labour,decision_making_mechanisms_include_leader_first_among_equals
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1
2,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0

## Culture/Values/Norms

In [42]:
# gov_df['Culture/Values/Norms'] = gov_df['Culture/Values/Norms'].fillna('')

In [43]:
# gov_df['Culture/Values/Norms']

In [44]:
# values_list = list(gov_df['Culture/Values/Norms'])

In [45]:
# values_test = values_list[0]
# values_test

In [46]:
# [v.strip() for v in values_test.split(',')]

In [47]:
# values_set = set()

In [48]:
# Create set of all values
# [values_set.update([v.strip() for v in values.split(',')]) for values in values_list]
# values_set

In [49]:
# values_set.remove('')

In [50]:
# values_set

In [51]:
"""
for value in values_set:
    value_str = value.lower().replace('/', '_').replace(' ','_').replace('(','').replace(')','') # Normalize text
    col_name = 'values_include_' + value_str
    gov_df[col_name] = np.where(gov_df['Culture/Values/Norms'].str.contains(value, regex=False), 1, 0)
"""

"\nfor value in values_set:\n    value_str = value.lower().replace('/', '_').replace(' ','_').replace('(','').replace(')','') # Normalize text\n    col_name = 'values_include_' + value_str\n    gov_df[col_name] = np.where(gov_df['Culture/Values/Norms'].str.contains(value, regex=False), 1, 0)\n"

## Institutions

In [52]:
# gov_df['Institutions'] = gov_df['Institutions'].fillna('')

In [53]:
# gov_df['Institutions']

In [54]:
# institutions_list = list(gov_df['Institutions'])

In [55]:
# institutions_list

In [56]:
# institutions_test = institutions_list[0]
# institutions_test

In [57]:
# [i.strip() for i in institutions_test.split(',')]

In [58]:
# institutions_set = set()

In [59]:
# String test
# "\'\'\"".strip().replace('"', '').replace('\'','')

In [60]:
# test_string = '"Hunting ""chief"""'
# test_string

In [61]:
# test_string.strip().replace('\"', '').replace('\'','')

In [62]:
# original_institutions_set = set()

In [63]:
# [original_institutions_set.update([i for i in institutions.split(',')]) for institutions in institutions_list]
# original_institutions_set

In [64]:
# Create set of all values
# [institutions_set.update([i.lower().strip() for i in institutions.split(',')]) for institutions in institutions_list]
# institutions_set

In [65]:
# len(institutions_set)

In [66]:
# Cleanup
# cleaned_institutions_set = {i.replace('\"', '').replace('\'','') for i in institutions_set}

In [67]:
# cleaned_institutions_set

In [68]:
# len(cleaned_institutions_set)

In [69]:
# institutions_set.difference(cleaned_institutions_set)

In [70]:
# cleaned_institutions_set.difference(institutions_set)

In [71]:
# gov_df['Institutions']

In [72]:
"""
for institution in original_institutions_set:
    institution_str = institution.lower() \
                                .replace('/', '_') \
                                .replace(' ','_') \
                                .replace('(','') \
                                .replace(')','') \
                                .replace('\"', '') \
                                .replace('\'','') # Normalize text
    col_name = 'institutions_include_' + institution_str
    gov_df[col_name] = np.where(gov_df['Institutions'].str.contains(institution, regex=False), 1, 0)
    
"""
# Exclude institutions for now

'\nfor institution in original_institutions_set:\n    institution_str = institution.lower()                                 .replace(\'/\', \'_\')                                 .replace(\' \',\'_\')                                 .replace(\'(\',\'\')                                 .replace(\')\',\'\')                                 .replace(\'"\', \'\')                                 .replace(\'\'\',\'\') # Normalize text\n    col_name = \'institutions_include_\' + institution_str\n    gov_df[col_name] = np.where(gov_df[\'Institutions\'].str.contains(institution, regex=False), 1, 0)\n\n'

In [73]:
# list(cleaned_institutions_set)

In [74]:
# list(gov_df)

In [75]:
# institution_columns = [col_name for col_name in list(gov_df) if 'institutions_include' in col_name]

In [76]:
# institution_columns

In [77]:
# gov_df[institution_columns].sum().sort_values()

In [78]:
# TODO: Institutions need cleanup, formatting is causing issues with encoding

In [79]:
# gov_df.head()

## Size

In [80]:
"""
Replace sizes:

100 - 1,000
1,001 - 10,000
20,000-30,000                  -> 10,001 - 100,000
33,000                         -> 10,001 - 100,000 
10,001 - 100,000
100,001 - 1 million members    -> 100,001 - 1,000,000
1 million - 10 million members -> 1,000,001 - 10,000,000
+10 million members            -> 10,000,000+
20 million - 30 million        -> 10,000,000+
Unknown
"""

'\nReplace sizes:\n\n100 - 1,000\n1,001 - 10,000\n20,000-30,000                  -> 10,001 - 100,000\n33,000                         -> 10,001 - 100,000 \n10,001 - 100,000\n100,001 - 1 million members    -> 100,001 - 1,000,000\n1 million - 10 million members -> 1,000,001 - 10,000,000\n+10 million members            -> 10,000,000+\n20 million - 30 million        -> 10,000,000+\nUnknown\n'

In [81]:
# Replace size values
gov_df['Size'] = gov_df['Size'].replace(['20,000-30,000','33,000'], '10,001 - 100,000')

In [82]:
gov_df['Size'] = gov_df['Size'].replace(['100,001 - 1 million members'], '100,001 - 1,000,000')

In [83]:
gov_df['Size'] = gov_df['Size'].replace(['1 million - 10 million members'], '1,000,001 - 10,000,000')

In [84]:
gov_df['Size'] = gov_df['Size'].replace(['+10 million members','20 million - 30 million'], '10,000,000+')

In [85]:
gov_df['Size'].value_counts()

Size
10,001 - 100,000          37
1,001 - 10,000            22
100,001 - 1,000,000       10
Unknown                    7
1,000,001 - 10,000,000     6
100 - 1,000                5
10,000,000+                4
Name: count, dtype: int64

In [86]:
size_order = [
    '100 - 1,000',
    '1,001 - 10,000',
    '10,001 - 100,000',
    '100,001 - 1,000,000',
    '1,000,001 - 10,000,000',
    '10,000,000+',
    'Unknown'
]

In [87]:
for size in size_order:
    col_name = 'Size: ' + size
    gov_df[col_name] = np.where(gov_df['Size'] == size, 1, 0)

/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/3608956748.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Size'] == size, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/3608956748.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Size'] == size, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/3608956748.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Size'] == size, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/3608956748.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Size'] == size, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/3608956748.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Size'] == size, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/3608956748.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Size'] == size, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/3608956748.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Size'] == size, 1, 0)

In [88]:
gov_df.head()

,Name,Institutions,Mechanism,Notes,Time span,Geography,Continent,Size,Source,Metanotes,Heterogeneity,FC comments,expert check,Time span: Start,Time span: End,SCCS,is_SCCS,enforcement_mechanisms_include_tribunal_court_,decision_making_mechanisms_include_checks_and_balances,decision_making_mechanisms_include_rule_of_law,enforcement_mechanisms_include_reputational_risk,decision_making_mechanisms_include_confederacy,decision_making_mechanisms_include_consultation,decision_making_mechanisms_include_power_fluidity,enforcement_mechanisms_include_police,decision_making_mechanisms_include_coalition,enforcement_mechanisms_include_fines,decision_making_mechanisms_include_veto,decision_making_mechanisms_include_majority_voting,enforcement_mechanisms_include_jury_judge,decision_making_mechanisms_include_mandate,enforcement_mechanisms_include_paying_damages_compensation,decision_making_mechanisms_include_bureaucracy,decision_making_mechanisms_include_word_of_mouth,decision_making_mechanisms_include_assembly_local,decision_making_mechanisms_include_dual-sex_political_system,enforcement_mechanisms_include_civil_disobedience,decision_making_mechanisms_include_assembly_elite,access_mechanisms_include_enfranchisement,decision_making_mechanisms_include_alliance,decision_making_mechanisms_include_kingchief-as-figurehead,decision_making_mechanisms_include_group_voting,decision_making_mechanisms_include_plurality_voting,decision_making_mechanisms_include_vote_by_show_of_hands,decision_making_mechanisms_include_delegation,decision_making_mechanisms_include_board_committee,access_mechanisms_include_screening_process,access_mechanisms_include_divine_right,enforcement_mechanisms_include_negotiation,decision_making_mechanisms_include_magistrate_official,decision_making_mechanisms_include_council_local,enforcement_mechanisms_include_mediation,decision_making_mechanisms_include_lobbying,enforcement_mechanisms_include_capital_punishment,access_mechanisms_include_lottery_random_selection,enforcement_mechanisms_include_graduated_sanctions,decision_making_mechanisms_include_frequent_and_or_regular_meetings,decision_making_mechanisms_include_gathering,access_mechanisms_include_dreaming,enforcement_mechanisms_include_criticism_mocking_joking,access_mechanisms_include_meritocracy,decision_making_mechanisms_include_agenda_setting,access_mechanisms_include_matriarchy,access_mechanisms_include_payment_for_occupying_office,access_mechanisms_include_child_participation,decision_making_mechanisms_include_secret_ballot,access_mechanisms_include_gerontocracy,decision_making_mechanisms_include_temporary_position_of_power_term_limits,enforcement_mechanisms_include_destruction_of_property,access_mechanisms_include_patronage_for_office,decision_making_mechanisms_include_turnover_rotation,access_mechanisms_include_heredity,decision_making_mechanisms_include_autocratic_leader_chief_bound,decision_making_mechanisms_include_assembly_central,enforcement_mechanisms_include_self-help,decision_making_mechanisms_include_petition,enforcement_mechanisms_include_suspension_expulsion_ostracism_proscription,access_mechanisms_include_blood_relations,enforcement_mechanisms_include_monitoring,enforcement_mechanisms_include_corporal_punishment_violence_against_perpetrator,decision_making_mechanisms_include_balance_of_power,decision_making_mechanisms_include_council_central_,access_mechanisms_include_female_participation,decision_making_mechanisms_include_deliberation,enforcement_mechanisms_include_exit,enforcement_mechanisms_include_appeal,access_mechanisms_include_popularity_,decision_making_mechanisms_include_unanimity,enforcement_mechanisms_include_judicial_review,decision_making_mechanisms_include_oath,decision_making_mechanisms_include_supermajority,enforcement_mechanisms_include_seizing_of_property,enforcement_mechanisms_include_arbitration,decision_making_mechanisms_include_remunerated_position,enforcement_mechanisms_include_litigation,decision_making_mechanisms_include_representation,decision_making_mechanisms_include_quorum,decision_making_mechanisms_include_consent,access_mechanisms_include_co-optation,decision_making_mechanisms_include_constitution,access_mechanisms_include_induction_rite_ceremony,enforcement_mechanisms_include_scrutiny_of_officials,decision_making_mechanisms_include_president_consul_chief_executive,decision_making_mechanisms_include_public_meetings,access_mechanisms_include_age_boundaries,decision_making_mechanisms_include_vote_by_proxy,decision_making_mechanisms_include_voting,access_mechanisms_include_matrilineality,decision_making_mechanisms_include_consensus,decision_making_mechanisms_include_ratification_acclamation_only,access_mechanisms_include_election,access_mechanisms_include_life_appointment,access_mechanisms_include_property_requirement,decision_making_mechanisms_include_autocratic_leader_unbound,access_mechanisms_include_open_political_unit,enforcement_mechanisms_include_forced_labour,decision_making_mechanisms_include_leader_first_among_equals,"Size: 100 - 1,000","Size: 1,001 - 10,000","Size: 10,001 - 100,000","Size: 100,001 - 1,000,000","Size: 1,000,001 - 10,000,000","Size: 10,000,000+",Size: Unknown
0,Aedui (Celtic Oppida),"Senatus,Elected magistrates,Assemblies","Election,Council (central) ,Assembly (central)...",There are many Celtic oppida throughout northe...,2nd-1st century BC,"Europe, North",Europe,"100,001 - 1,000,000","Collis, “Celtic” Oppida, in Hansen, A Comparat...",NaN,NaN,Edited March 23,NaN,-200,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0
1,Akha,"Council of Elders,Village Founder-Leader (dzom...","Leader (first among equals),Gerontocracy,Blood...",see Institutions tab,20th century - Present,"Asia, Southeast",Asia,"10,001 - 100,000","Main: \nKammerer, Cornelia Ann (1985/86), Gate...",NaN,"Informal inclusion,Gender groups,Informal powe...",Edited May 23,NaN,1900,2023,NaN,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
2,Amalfi,"Prefetturii/ Conti/ Dogi,Sedile di congrega,Ta...","Election,Magistrate/official,Heredity,Constitu...","Camera, M, p. 29 (""La sua popolazione che nel ...",4th-12th century AD,"Europe, West",Europe,"10,001 - 100,000","Camera, M. Istoria della città e costiera di A...",NaN,NaN,Edited March 23 (could use more info on CGIs),NaN,300,1200,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
3,Arab nomads,"shaykh or sayyid,shura or mashwara","Consensus,Consultation,Autocratic Leader/Chief...",Nomadic Bedouin society governed by rulers sel...,"1st-7th century AD\n(start date is arbitrary, ...","Asia, Middle East",Asia,Unknown,"Stasavage, David (2020), The Decline and Rise ...",NaN,NaN,Edited Feb 23 (could use additional sources fo...,NaN,0,700,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,Assur,"King,Alum,Limmum,Scribe,City hall","President/Consul/Chief Executive,Assembly (cen...",Independent city-state. Constitutional monarch...,19th century BC\n(1920-1800 BC),"Asia, Southwest, Anatolia",Asia,"1,001 - 10,000","Larsen, M. T. The Old Assyrian City-State in H...",NaN,NaN,Edited Mar 23,Giacomo CHECKED,-1920,-1800,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0

## Geography

In [89]:
list(gov_df)

['Name',
 'Institutions',
 'Mechanism',
 'Notes',
 'Time span',
 'Geography',
 'Continent',
 'Size',
 'Source',
 'Metanotes',
 'Heterogeneity ',
 'FC comments',
 'expert check',
 'Time span: Start',
 'Time span: End',
 'SCCS',
 'is_SCCS',
 'enforcement_mechanisms_include_tribunal_court_',
 'decision_making_mechanisms_include_checks_and_balances',
 'decision_making_mechanisms_include_rule_of_law',
 'enforcement_mechanisms_include_reputational_risk',
 'decision_making_mechanisms_include_confederacy',
 'decision_making_mechanisms_include_consultation',
 'decision_making_mechanisms_include_power_fluidity',
 'enforcement_mechanisms_include_police',
 'decision_making_mechanisms_include_coalition',
 'enforcement_mechanisms_include_fines',
 'decision_making_mechanisms_include_veto',
 'decision_making_mechanisms_include_majority_voting',
 'enforcement_mechanisms_include_jury_judge',
 'decision_making_mechanisms_include_mandate',
 'enforcement_mechanisms_include_paying_damages_compensation',
 'decision_making_mechanisms_include_bureaucracy',
 'decision_making_mechanisms_include_word_of_mouth',
 'decision_making_mechanisms_include_assembly_local',
 'decision_making_mechanisms_include_dual-sex_political_system',
 'enforcement_mechanisms_include_civil_disobedience',
 'decision_making_mechanisms_include_assembly_elite',
 'access_mechanisms_include_enfranchisement',
 'decision_making_mechanisms_include_alliance',
 'decision_making_mechanisms_include_kingchief-as-figurehead',
 'decision_making_mechanisms_include_group_voting',
 'decision_making_mechanisms_include_plurality_voting',
 'decision_making_mechanisms_include_vote_by_show_of_hands',
 'decision_making_mechanisms_include_delegation',
 'decision_making_mechanisms_include_board_committee',
 'access_mechanisms_include_screening_process',
 'access_mechanisms_include_divine_right',
 'enforcement_mechanisms_include_negotiation',
 'decision_making_mechanisms_include_magistrate_official',
 'decision_making_mechanisms_include_council_local',
 'enforcement_mechanisms_include_mediation',
 'decision_making_mechanisms_include_lobbying',
 'enforcement_mechanisms_include_capital_punishment',
 'access_mechanisms_include_lottery_random_selection',
 'enforcement_mechanisms_include_graduated_sanctions',
 'decision_making_mechanisms_include_frequent_and_or_regular_meetings',
 'decision_making_mechanisms_include_gathering',
 'access_mechanisms_include_dreaming',
 'enforcement_mechanisms_include_criticism_mocking_joking',
 'access_mechanisms_include_meritocracy',
 'decision_making_mechanisms_include_agenda_setting',
 'access_mechanisms_include_matriarchy',
 'access_mechanisms_include_payment_for_occupying_office',
 'access_mechanisms_include_child_participation',
 'decision_making_mechanisms_include_secret_ballot',
 'access_mechanisms_include_gerontocracy',
 'decision_making_mechanisms_include_temporary_position_of_power_term_limits',
 'enforcement_mechanisms_include_destruction_of_property',
 'access_mechanisms_include_patronage_for_office',
 'decision_making_mechanisms_include_turnover_rotation',
 'access_mechanisms_include_heredity',
 'decision_making_mechanisms_include_autocratic_leader_chief_bound',
 'decision_making_mechanisms_include_assembly_central',
 'enforcement_mechanisms_include_self-help',
 'decision_making_mechanisms_include_petition',
 'enforcement_mechanisms_include_suspension_expulsion_ostracism_proscription',
 'access_mechanisms_include_blood_relations',
 'enforcement_mechanisms_include_monitoring',
 'enforcement_mechanisms_include_corporal_punishment_violence_against_perpetrator',
 'decision_making_mechanisms_include_balance_of_power',
 'decision_making_mechanisms_include_council_central_',
 'access_mechanisms_include_female_participation',
 'decision_making_mechanisms_include_deliberation',
 'enforcement_mechanisms_include_exit',
 'enforcement_mechanisms_include_appeal',
 'access_mechanisms_include_popularity_',
 'decision_making_mechanisms_include_unanimity',
 'enforcement_mechanisms_include_judicial_review',
 'decision_making_mechanisms_include_oath',
 'decision_making_mechanisms_include_supermajority',
 'enforcement_mechanisms_include_seizing_of_property',
 'enforcement_mechanisms_include_arbitration',
 'decision_making_mechanisms_include_remunerated_position',
 'enforcement_mechanisms_include_litigation',
 'decision_making_mechanisms_include_representation',
 'decision_making_mechanisms_include_quorum',
 'decision_making_mechanisms_include_consent',
 'access_mechanisms_include_co-optation',
 'decision_making_mechanisms_include_constitution',
 'access_mechanisms_include_induction_rite_ceremony',
 'enforcement_mechanisms_include_scrutiny_of_officials',
 'decision_making_mechanisms_include_president_consul_chief_executive',
 'decision_making_mechanisms_include_public_meetings',
 'access_mechanisms_include_age_boundaries',
 'decision_making_mechanisms_include_vote_by_proxy',
 'decision_making_mechanisms_include_voting',
 'access_mechanisms_include_matrilineality',
 'decision_making_mechanisms_include_consensus',
 'decision_making_mechanisms_include_ratification_acclamation_only',
 'access_mechanisms_include_election',
 'access_mechanisms_include_life_appointment',
 'access_mechanisms_include_property_requirement',
 'decision_making_mechanisms_include_autocratic_leader_unbound',
 'access_mechanisms_include_open_political_unit',
 'enforcement_mechanisms_include_forced_labour',
 'decision_making_mechanisms_include_leader_first_among_equals',
 'Size: 100 - 1,000',
 'Size: 1,001 - 10,000',
 'Size: 10,001 - 100,000',
 'Size: 100,001 - 1,000,000',
 'Size: 1,000,001 - 10,000,000',
 'Size: 10,000,000+',
 'Size: Unknown']

In [90]:
geography_list = gov_df['Geography'].unique()

In [91]:
geography_list

array(['Europe, North', 'Asia, Southeast ', 'Europe, West',
       'Asia, Middle East', 'Asia, Southwest, Anatolia', 'Europe, South',
       'North America, Central America', 'Asia, Middle East, Mesopotamia',
       'Africa, North ', 'Africa, Central', 'Asia, China', 'Europe, East',
       'Africa, North', 'Africa, South, Botswana', 'Europe, Italy',
       'Europe, South, Greece', 'North America', 'Africa, West, Nigeria',
       'Asia, Southeast', 'Africa, West, Mid-western Nigeria',
       'Africa, West, Niger Delta', 'Asia, India (northeast)',
       'Asia, Japan', 'Asia, North-eastern India', 'Africa South',
       'Europe South, Italy', 'Africa, North, Algeria', 'Asia, Central',
       'Asia, Southwestern China', 'South America, Brazil',
       'North America, Louisiana', 'Asia, Southeast, Bali',
       'North America, Central America, Mexico', 'Asia, India',
       'Asia, Middle East ', 'Europe, South, Italy',
       'South America, Patagonia', 'South America, Venezuela/Brazil',
       'Oceania, New Caledonia', 'Oceania, New Zealand',
       'Oceania, eastern Polynesia', 'Oceania, samoa',
       'Oceania, Kiribati', 'Asia, South', 'Asia, East', 'Africa',
       'North America, Alaska', 'North America, Canada'], dtype=object)

In [92]:
for geography in geography_list:
    col_name = 'Geography: ' + geography
    gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)

/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/2328290932.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Geography'] == geography, 1, 0)

### Encode Regions

In [93]:
# regions = ['Africa','Europe','Asia','Middle East','North America','Central America','South America','Oceania']

In [94]:
gov_df['Geography']

0                              Europe, North
1                           Asia, Southeast
2                               Europe, West
3                          Asia, Middle East
4                  Asia, Southwest, Anatolia
5                              Europe, South
6             North America, Central America
7             Asia, Middle East, Mesopotamia
8                             Africa, North
9                            Africa, Central
10                               Asia, China
11                              Europe, East
12                              Europe, West
13                              Europe, West
14                             Europe, North
15                         Asia, Middle East
16                             Africa, North
17                              Europe, West
18                   Africa, South, Botswana
19                             Europe, Italy
20                             Europe, Italy
21                     Europe, South, Greece
22                     Europe, South, Greece
23                             North America
24                     Africa, West, Nigeria
25                           Asia, Southeast
26                             Europe, North
27         Africa, West, Mid-western Nigeria
28                 Africa, West, Niger Delta
29                              Europe, West
30                   Asia, India (northeast)
31                   Asia, India (northeast)
32                   Asia, India (northeast)
33                               Asia, Japan
34                           Asia, Southeast
35                 Asia, North-eastern India
36                              Africa South
37                       Europe South, Italy
38                    Africa, North, Algeria
39                             North America
40                         Asia, Middle East
41                           Asia, Southeast
42            North America, Central America
43                             North America
44                             Asia, Central
45                  Asia, Southwestern China
46                     South America, Brazil
47                  North America, Louisiana
48                              Europe, East
49                     Asia, Southeast, Bali
50                             North America
51    North America, Central America, Mexico
52                               Asia, India
53                        Asia, Middle East
54                      Europe, South, Italy
55                             North America
56                      Europe, South, Italy
57                              Europe, East
58                             Europe, Italy
59                         Asia, Middle East
60                              Europe, West
61                          Asia, Southeast
62            North America, Central America
63                      Europe, South, Italy
64                             North America
65                  South America, Patagonia
66                     South America, Brazil
67           South America, Venezuela/Brazil
68                    Oceania, New Caledonia
69                      Oceania, New Zealand
70                Oceania, eastern Polynesia
71                            Oceania, samoa
72                         Oceania, Kiribati
73                               Asia, South
74                               Asia, South
75                                Asia, East
76                                    Africa
77                                    Africa
78                                    Africa
79                                    Africa
80                                    Africa
81                     North America, Alaska
82                     North America, Canada
83                     North America, Canada
84                             North America
85                             North America
86                             North America
87                             North America
88                             North America
89                             North America
90            North America, Central America
Name: Geography, dtype: object

In [95]:
'''
# Create broader regions 
def assign_regions(geography):
    for region in regions:
        if region in geography:
            return region
    return 'Other'
'''

"\n# Create broader regions \ndef assign_regions(geography):\n    for region in regions:\n        if region in geography:\n            return region\n    return 'Other'\n"

In [96]:
# gov_df['Region'] = gov_df['Geography'].apply(assign_regions)

In [97]:
# gov_df['Region']

In [98]:
# gov_df['Region'].value_counts()

In [99]:
# gov_df['Region'].value_counts().sum()

In [100]:
'''
for region in regions:
    col_name = 'Region: ' + region
    gov_df[col_name] = np.where(gov_df['Region'] == region, 1, 0)
'''

"\nfor region in regions:\n    col_name = 'Region: ' + region\n    gov_df[col_name] = np.where(gov_df['Region'] == region, 1, 0)\n"

In [101]:
gov_df.head()

,Name,Institutions,Mechanism,Notes,Time span,Geography,Continent,Size,Source,Metanotes,Heterogeneity,FC comments,expert check,Time span: Start,Time span: End,SCCS,is_SCCS,enforcement_mechanisms_include_tribunal_court_,decision_making_mechanisms_include_checks_and_balances,decision_making_mechanisms_include_rule_of_law,enforcement_mechanisms_include_reputational_risk,decision_making_mechanisms_include_confederacy,decision_making_mechanisms_include_consultation,decision_making_mechanisms_include_power_fluidity,enforcement_mechanisms_include_police,decision_making_mechanisms_include_coalition,enforcement_mechanisms_include_fines,decision_making_mechanisms_include_veto,decision_making_mechanisms_include_majority_voting,enforcement_mechanisms_include_jury_judge,decision_making_mechanisms_include_mandate,enforcement_mechanisms_include_paying_damages_compensation,decision_making_mechanisms_include_bureaucracy,decision_making_mechanisms_include_word_of_mouth,decision_making_mechanisms_include_assembly_local,decision_making_mechanisms_include_dual-sex_political_system,enforcement_mechanisms_include_civil_disobedience,decision_making_mechanisms_include_assembly_elite,access_mechanisms_include_enfranchisement,decision_making_mechanisms_include_alliance,decision_making_mechanisms_include_kingchief-as-figurehead,decision_making_mechanisms_include_group_voting,decision_making_mechanisms_include_plurality_voting,decision_making_mechanisms_include_vote_by_show_of_hands,decision_making_mechanisms_include_delegation,decision_making_mechanisms_include_board_committee,access_mechanisms_include_screening_process,access_mechanisms_include_divine_right,enforcement_mechanisms_include_negotiation,decision_making_mechanisms_include_magistrate_official,decision_making_mechanisms_include_council_local,enforcement_mechanisms_include_mediation,decision_making_mechanisms_include_lobbying,enforcement_mechanisms_include_capital_punishment,access_mechanisms_include_lottery_random_selection,enforcement_mechanisms_include_graduated_sanctions,decision_making_mechanisms_include_frequent_and_or_regular_meetings,decision_making_mechanisms_include_gathering,access_mechanisms_include_dreaming,enforcement_mechanisms_include_criticism_mocking_joking,access_mechanisms_include_meritocracy,decision_making_mechanisms_include_agenda_setting,access_mechanisms_include_matriarchy,access_mechanisms_include_payment_for_occupying_office,access_mechanisms_include_child_participation,decision_making_mechanisms_include_secret_ballot,access_mechanisms_include_gerontocracy,decision_making_mechanisms_include_temporary_position_of_power_term_limits,enforcement_mechanisms_include_destruction_of_property,access_mechanisms_include_patronage_for_office,decision_making_mechanisms_include_turnover_rotation,access_mechanisms_include_heredity,decision_making_mechanisms_include_autocratic_leader_chief_bound,decision_making_mechanisms_include_assembly_central,enforcement_mechanisms_include_self-help,decision_making_mechanisms_include_petition,enforcement_mechanisms_include_suspension_expulsion_ostracism_proscription,access_mechanisms_include_blood_relations,enforcement_mechanisms_include_monitoring,enforcement_mechanisms_include_corporal_punishment_violence_against_perpetrator,decision_making_mechanisms_include_balance_of_power,decision_making_mechanisms_include_council_central_,access_mechanisms_include_female_participation,decision_making_mechanisms_include_deliberation,enforcement_mechanisms_include_exit,enforcement_mechanisms_include_appeal,access_mechanisms_include_popularity_,decision_making_mechanisms_include_unanimity,enforcement_mechanisms_include_judicial_review,decision_making_mechanisms_include_oath,decision_making_mechanisms_include_supermajority,enforcement_mechanisms_include_seizing_of_property,enforcement_mechanisms_include_arbitration,decision_making_mechanisms_include_remunerated_position,enforcement_mechanisms_include_litigation,decision_making_mechanisms_include_representation,decision_making_mechanisms_include_quorum,decision_making_mechanisms_include_consent,access_mechanisms_include_co-optation,decision_making_mechanisms_include_constitution,access_mechanisms_include_induction_rite_ceremony,enforcement_mechanisms_include_scrutiny_of_officials,decision_making_mechanisms_include_president_consul_chief_executive,decision_making_mechanisms_include_public_meetings,access_mechanisms_include_age_boundaries,decision_making_mechanisms_include_vote_by_proxy,decision_making_mechanisms_include_voting,access_mechanisms_include_matrilineality,decision_making_mechanisms_include_consensus,decision_making_mechanisms_include_ratification_acclamation_only,access_mechanisms_include_election,access_mechanisms_include_life_appointment,access_mechanisms_include_property_requirement,decision_making_mechanisms_include_autocratic_leader_unbound,access_mechanisms_include_open_political_unit,enforcement_mechanisms_include_forced_labour,decision_making_mechanisms_include_leader_first_among_equals,"Size: 100 - 1,000","Size: 1,001 - 10,000","Size: 10,001 - 100,000","Size: 100,001 - 1,000,000","Size: 1,000,001 - 10,000,000","Size: 10,000,000+",Size: Unknown,"Geography: Europe, North","Geography: Asia, Southeast","Geography: Europe, West","Geography: Asia, Middle East","Geography: Asia, Southwest, Anatolia","Geography: Europe, South","Geography: North America, Central America","Geography: Asia, Middle East, Mesopotamia","Geography: Africa, North","Geography: Africa, Central","Geography: Asia, China","Geography: Europe, East","Geography: Africa, North","Geography: Africa, South, Botswana","Geography: Europe, Italy","Geography: Europe, South, Greece",Geography: North America,"Geography: Africa, West, Nigeria","Geography: Asia, Southeast","Geography: Africa, West, Mid-western Nigeria","Geography: Africa, West, Niger Delta","Geography: Asia, India (northeast)","Geography: Asia, Japan","Geography: Asia, North-eastern India",Geography: Africa South,"Geography: Europe South, Italy","Geography: Africa, North, Algeria","Geography: Asia, Central","Geography: Asia, Southwestern China","Geography: South America, Brazil","Geography: North America, Louisiana","Geography: Asia, Southeast, Bali","Geography: North America, Central America, Mexico","Geography: Asia, India","Geography: Asia, Middle East","Geography: Europe, South, Italy","Geography: South America, Patagonia","Geography: South America, Venezuela/Brazil","Geography: Oceania, New Caledonia","Geography: Oceania, New Zealand","Geography: Oceania, eastern Polynesia","Geography: Oceania, samoa","Geography: Oceania, Kiribati","Geography: Asia, South","Geography: Asia, East",Geography: Africa,"Geography: North America, Alaska","Geography: North America, Canada"
0,Aedui (Celtic Oppida),"Senatus,Elected magistrates,Assemblies","Election,Council (central) ,Assembly (central)...",There are many Celtic oppida throughout northe...,2nd-1st century BC,"Europe, North",Europe,"100,001 - 1,000,000","Collis, “Celtic” Oppida, in Hansen, A Comparat...",NaN,NaN,Edited March 23,NaN,-200,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Akha,"Council of Elders,Village Founder-Leader (dzom...","Leader (first among equals),Gerontocracy,Blood...",see Institutions tab,20th century - Present,"Asia, Southeast",Asia,"10,001 - 100,000","Main: \nKammerer, Cornelia Ann (1985/86), Gate...",NaN,"Informal inclusion,Gender groups,Informal powe...",Edited May 23,NaN,1900,2023,NaN,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Amalfi,"Prefetturii/ Conti/ Dogi,Sedile di congrega,Ta...","Election,Magistrate/official,Heredity,Constitu...","Camera, M, p. 29 (""La sua popolazione che nel ...",4th-12th century AD,"Europe, West",Europe,"10,001 - 100,000","Camera, M. Istoria della città e costiera di A...",NaN,NaN,Edited March 23 (could use more info on CGIs),NaN,300,1200,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Arab nomads,"shaykh or sayyid,shura or mashwara","Consensus,Consultation,Autocratic Leader/Chief...",Nomadic Bedouin society governed by rulers sel...,"1st-7th century AD\n(start date is arbitrary, ...","Asia, Middle East",Asia,Unknown,"Stasavage, David (2020), The Decline and Rise ...",NaN,NaN,Edited Feb 23 (could use additional sources fo...,NaN,0,700,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Assur,"King,Alum,Limmum,Scribe,City hall","President/Consul/Chief Executive,Assembly (cen...",Independent city-state. Constitutional monarch...,19th century BC\n(1920-1800 BC),"Asia, Southwest, Anatolia",Asia,"1,001 - 10,000","Larsen, M. T. The Old Assyrian City-State in H...",NaN,NaN,Edited Mar 23,Giacomo CHECKED,-1920,-1800,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [102]:
### Continents

In [103]:
gov_df['Continent'].value_counts()

Continent
Asia             25
Europe           22
North America    21
Africa           14
Oceania           5
South America     4
Name: count, dtype: int64

In [104]:
continents = ['Asia', 'Europe', 'North America', 'Africa', 'Oceania', 'South America', 'Antarctica']

In [105]:
# Encode Continents
for continent in continents:
    col_name = 'Continent: ' + continent
    gov_df[col_name] = np.where(gov_df['Continent'] == continent, 1, 0)

/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/1130556903.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Continent'] == continent, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/1130556903.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Continent'] == continent, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/1130556903.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Continent'] == continent, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/1130556903.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Continent'] == continent, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/1130556903.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Continent'] == continent, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/1130556903.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Continent'] == continent, 1, 0)
/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/1130556903.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df[col_name] = np.where(gov_df['Continent'] == continent, 1, 0)

In [106]:
gov_df

,Name,Institutions,Mechanism,Notes,Time span,Geography,Continent,Size,Source,Metanotes,Heterogeneity,FC comments,expert check,Time span: Start,Time span: End,SCCS,is_SCCS,enforcement_mechanisms_include_tribunal_court_,decision_making_mechanisms_include_checks_and_balances,decision_making_mechanisms_include_rule_of_law,enforcement_mechanisms_include_reputational_risk,decision_making_mechanisms_include_confederacy,decision_making_mechanisms_include_consultation,decision_making_mechanisms_include_power_fluidity,enforcement_mechanisms_include_police,decision_making_mechanisms_include_coalition,enforcement_mechanisms_include_fines,decision_making_mechanisms_include_veto,decision_making_mechanisms_include_majority_voting,enforcement_mechanisms_include_jury_judge,decision_making_mechanisms_include_mandate,enforcement_mechanisms_include_paying_damages_compensation,decision_making_mechanisms_include_bureaucracy,decision_making_mechanisms_include_word_of_mouth,decision_making_mechanisms_include_assembly_local,decision_making_mechanisms_include_dual-sex_political_system,enforcement_mechanisms_include_civil_disobedience,decision_making_mechanisms_include_assembly_elite,access_mechanisms_include_enfranchisement,decision_making_mechanisms_include_alliance,decision_making_mechanisms_include_kingchief-as-figurehead,decision_making_mechanisms_include_group_voting,decision_making_mechanisms_include_plurality_voting,decision_making_mechanisms_include_vote_by_show_of_hands,decision_making_mechanisms_include_delegation,decision_making_mechanisms_include_board_committee,access_mechanisms_include_screening_process,access_mechanisms_include_divine_right,enforcement_mechanisms_include_negotiation,decision_making_mechanisms_include_magistrate_official,decision_making_mechanisms_include_council_local,enforcement_mechanisms_include_mediation,decision_making_mechanisms_include_lobbying,enforcement_mechanisms_include_capital_punishment,access_mechanisms_include_lottery_random_selection,enforcement_mechanisms_include_graduated_sanctions,decision_making_mechanisms_include_frequent_and_or_regular_meetings,decision_making_mechanisms_include_gathering,access_mechanisms_include_dreaming,enforcement_mechanisms_include_criticism_mocking_joking,access_mechanisms_include_meritocracy,decision_making_mechanisms_include_agenda_setting,access_mechanisms_include_matriarchy,access_mechanisms_include_payment_for_occupying_office,access_mechanisms_include_child_participation,decision_making_mechanisms_include_secret_ballot,access_mechanisms_include_gerontocracy,decision_making_mechanisms_include_temporary_position_of_power_term_limits,enforcement_mechanisms_include_destruction_of_property,access_mechanisms_include_patronage_for_office,decision_making_mechanisms_include_turnover_rotation,access_mechanisms_include_heredity,decision_making_mechanisms_include_autocratic_leader_chief_bound,decision_making_mechanisms_include_assembly_central,enforcement_mechanisms_include_self-help,decision_making_mechanisms_include_petition,enforcement_mechanisms_include_suspension_expulsion_ostracism_proscription,access_mechanisms_include_blood_relations,enforcement_mechanisms_include_monitoring,enforcement_mechanisms_include_corporal_punishment_violence_against_perpetrator,decision_making_mechanisms_include_balance_of_power,decision_making_mechanisms_include_council_central_,access_mechanisms_include_female_participation,decision_making_mechanisms_include_deliberation,enforcement_mechanisms_include_exit,enforcement_mechanisms_include_appeal,access_mechanisms_include_popularity_,decision_making_mechanisms_include_unanimity,enforcement_mechanisms_include_judicial_review,decision_making_mechanisms_include_oath,decision_making_mechanisms_include_supermajority,enforcement_mechanisms_include_seizing_of_property,enforcement_mechanisms_include_arbitration,decision_making_mechanisms_include_remunerated_position,enforcement_mechanisms_include_litigation,decision_making_mechanisms_include_representation,decision_making_mechanisms_include_quorum,decision_making_mechanisms_include_consent,access_mechanisms_include_co-optation,decision_making_mechanisms_include_constitution,access_mechanisms_include_induction_rite_ceremony,enforcement_mechanisms_include_scrutiny_of_officials,decision_making_mechanisms_include_president_consul_chief_executive,decision_making_mechanisms_include_public_meetings,access_mechanisms_include_age_boundaries,decision_making_mechanisms_include_vote_by_proxy,decision_making_mechanisms_include_voting,access_mechanisms_include_matrilineality,decision_making_mechanisms_include_consensus,decision_making_mechanisms_include_ratification_acclamation_only,access_mechanisms_include_election,access_mechanisms_include_life_appointment,access_mechanisms_include_property_requirement,decision_making_mechanisms_include_autocratic_leader_unbound,access_mechanisms_include_open_political_unit,enforcement_mechanisms_include_forced_labour,decision_making_mechanisms_include_leader_first_among_equals,"Size: 100 - 1,000","Size: 1,001 - 10,000","Size: 10,001 - 100,000","Size: 100,001 - 1,000,000","Size: 1,000,001 - 10,000,000","Size: 10,000,000+",Size: Unknown,"Geography: Europe, North","Geography: Asia, Southeast","Geography: Europe, West","Geography: Asia, Middle East","Geography: Asia, Southwest, Anatolia","Geography: Europe, South","Geography: North America, Central America","Geography: Asia, Middle East, Mesopotamia","Geography: Africa, North","Geography: Africa, Central","Geography: Asia, China","Geography: Europe, East","Geography: Africa, North","Geography: Africa, South, Botswana","Geography: Europe, Italy","Geography: Europe, South, Greece",Geography: North America,"Geography: Africa, West, Nigeria","Geography: Asia, Southeast","Geography: Africa, West, Mid-western Nigeria","Geography: Africa, West, Niger Delta","Geography: Asia, India (northeast)","Geography: Asia, Japan","Geography: Asia, North-eastern India",Geography: Africa South,"Geography: Europe South, Italy","Geography: Africa, North, Algeria","Geography: Asia, Central","Geography: Asia, Southwestern China","Geography: South America, Brazil","Geography: North America, Louisiana","Geography: Asia, Southeast, Bali","Geography: North America, Central America, Mexico","Geography: Asia, India","Geography: Asia, Middle East","Geography: Europe, South, Italy","Geography: South America, Patagonia","Geography: South America, Venezuela/Brazil","Geography: Oceania, New Caledonia","Geography: Oceania, New Zealand","Geography: Oceania, eastern Polynesia","Geography: Oceania, samoa","Geography: Oceania, Kiribati","Geography: Asia, South","Geography: Asia, East",Geography: Africa,"Geography: North America, Alaska","Geography: North America, Canada",Continent: Asia,Continent: Europe,Continent: North America,Continent: Africa,Continent: Oceania,Continent: South America,Continent: Antarctica
0,Aedui (Celtic Oppida),"Senatus,Elected magistrates,Assemblies","Election,Council (central) ,Assembly (central)...",There are many Celtic oppida throughout northe...,2nd-1st century BC,"Europe, North",Europe,"100,001 - 1,000,000","Collis, “Celtic” Oppida, in Hansen, A Comparat...",NaN,NaN,Edited March 23,NaN,-200,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
1,Akha,"Council of Elders,Village Founder-Leader (dzom...","Leader (first among equals),Gerontocracy,Blood...",see Institutions tab,20th century - Present,"Asia, Southeast",Asia,"10,001 - 100,000","Main: \nKammerer, Cornelia Ann (1985/86), Gate...",NaN,"Informal inclusion,Gender groups,Informal powe...",Edited May 23,NaN,1900,2023,NaN,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
2,Amalfi,"Prefetturii/ Conti/ Dogi,Sedile di congrega,Ta...","Election,Magistrate/official,Heredity,Constitu...","Camera, M, p. 29 (""La sua popolazione che nel ...",4th-12th century AD,"Europe, West",Europe,"10,001 - 100,000","Camera, M. Istoria della città e costiera di A...",NaN,NaN,Edited March 23 (could use more info on CGIs),NaN,300,1200,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
3,Arab nomads,"shaykh or sayyid,shura or mashwara","Consensus,Consultation,Autocratic Leader/Chief...",Nomadic Bedouin society governed by rulers sel...,"1st-7th century AD\n(start date is arbitrary, ...","Asia, Middle East",Asia,Unknown,"Stasavage, David (2020), The Decline and Rise ...",NaN,NaN,Edited Feb 23 (could use additional sources fo...,NaN,0,700,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
4,Assur,"King,Alum,Limmum,Scribe,City hall","President/Consul/Chief Executive,Assembly (cen...",Independent city-state. Constitutional monarch...,19th century BC\n(1920-1800 BC),"Asia, Southwest, Anatolia",Asia,"1,001 - 10,000","Larsen, M. T. The Old Assyrian City-State in H...",NaN,NaN,Edited Mar 23,Giacomo CHECKED,-1920,-1800,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
5,Athens (Classical Period),"Council of Five Hundred (Boule),Areopagus,Ekkl...","Election,Plurality voting,Temporary position o...",'Cleisthenes reorganized Athens into 139 demes...,5th-4th century BC (508-322 BC),"Europe, South",Europe,"100,001 - 1,000,000","Stasavage, David (2020), The Decline and Rise ...",NaN,NaN,Edited Mar 23,NaN,-508,-322,NaN,0,1,0,1,0,0,0,0,0,0,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,1,0,0,1,0,0,0,1,1,0,1,0,0,1,0,1,0,0,0,1,0,1,0,0,1,0,0,1,1,0,1,0,1,1,0,1,0,1,0,0,0,0,1,1,0,1,1,1,1,0,1,1,0,1,0,1,0,1,1,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
6,Aztec City-States,"Tlatoani,Council of high nobles","Autocratic Leader/Chief (bound),Heredity,Merit...",BOUNDARY CASE: there is a council but degree ...,12th - 16th century AD,"North America, Central America",North America,"100,001 - 1,000,000","Michael E. Smith, Aztec City-States, in Hansen...",NaN,NaN,Edited May 23,NaN,1100,1600,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
7,Babylonia,"Governor,Council of Elders,The citizens/The As...","Assembly (central),Checks and balances,Consent...",The city-states of southern Mesopotamia in the...,9th-7th century BC,"Asia, Middle East, Mesopotamia",Asia,"10,001 - 100,000","Larsen, The City-States of the Early Neo-Babyl...",NaN,NaN,Edited Mar 23,Giacomo CHECKED,-900,-600,yes,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
8,Carthage,"Rab kohanim,Council of Elders,Tribunal of 104,...","Blood relations,Tribunal/Court ,Suspension/Exp...",'While it is true that Carthage had a range of...,4th-2nd century BC,"Africa, North",Africa,"100,001 - 1,000,000","Docter, Roald (2015), Punic Carthage, in Carth...",NaN,NaN,Edited Feb 23 (Additional sources can be used ...,NaN,-400,-100,NaN,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
9,Central African communities,"Big man,Council,ngongo munene","Leader (first among equals),Heredity,Matriline...",Villages spread across a large region. Politic...,10th -15th century AD\n(start date is arbitrar...,"Africa, Central",Africa,"10,001 - 100,000","Vansina, Jan (2004), How Societies Are Born: G...",From Owusu's chapter on Africa in the Edinburg...,NaN,Edited Apr 23,we need someone who can check the early 20th c...,900,1500,NaN,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
10,China (Spring and Autumn),"Zhou King,Ba,Assembly of the leading states,Gu...","Magistrate/official,Consultation,Heredity,Publ...",Between collapse of Zhang monarchy and the war...,8th -5th century BC\n(771-481BC),"Asia, China",Asia,"10,000,000+","Stasavage, David (2020), The Decline and Rise ...",NaN,NaN,Edited May 23,NaN,-771,-221,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
11,Circassians,Council of Matriarchs,"Council (central) ,Gerontocracy,Matriarchy,Fem...",'female warriors played a direct—even dominant...,12th-8th centuries BC,"Europe, East",Europe,Unknown,"Stasavage, David (2020), The Decline and Rise ...",NaN,NaN,Edited May 23,NaN,-1200,-700,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
12,Cologne,"Rentmeister,City council,Rentkammern","Co-optation,Temporary position of power/Term L...",Merchant oligarchy. Focus on the 12-13th centu...,13th - 14th century AD,"Europe, West",Europe,"10,001 - 100,000","Stasavage, David (2011), States of credit: siz...",NaN,NaN,Edited Feb 23 (Cologne is also a Free Imperial...,NaN,1200,1400,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
13,Communes (Medieval Europe),"King,Assembly","Autocratic Leader/Chief (bound),Consultation,A...",Municipal self-governance under a monarch resp...,10th-13th century AD,"Europe, West",Europe,"10,001 - 100,000","Reynolds, Kingdoms and communities in Western ...",NaN,NaN,Edited Jun 23 (Could use more specific sources),NaN,900,1200,NaN,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
14,Dutch Republic,"Vroedschap,Magistracies (WEST),Stadholder,Stat...","Assembly (central),Confederacy,Turnover/rotati...","Federation of 7 provinces, representing 57 tow...",16-18th century AD,"Europe, North",Europe,"10,001 - 100,000","Maarten Prak, The Dutch Republic's City-State ...",NaN,NaN,Edited March 23,NaN,1500,1800,NaN,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
15,Ebla,"En (malkum),Ø,Lugal,Abba,Notables/ Officials,L...","Autocratic Leader/Chief (bound),Council (centr...",Territorial kingdom subdivided in districts ea...,24th century BC \n(2400-2300 BC),"Asia, Middle East",Asia,"10,001 - 100,000","Benati, G. and Bonechi, M., 2020, ""The Fiscal ...",NaN,NaN,Edited jun 23,Giacomo CHECKED,-2400,-2300,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
16,Egypt,"Pharaoh,Vizier (t3.ty),'Overseer of the Treasu...","Petition,Autocratic Leader (unbound),Divine ri...","Entry focuses on the middle kingdom, when we h...",27th-11th century BC\n\nOld Kingdom: 2700-2200...,"Africa, North",Africa,"1,000,001 - 10,000,000","'- Alexandre Alexandrovich Loktionov, Inclusiv...",NaN,NaN,Edited May 23,ALEX CHECKED,-2700,-1000,NaN,0,1,0,0,0,0,1,0,1,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,1,0,1,0,0,1,1,0,1,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
17,England (Anglo Saxon),"witan,shire reeve,shire court,wapentake,gemot,...","Autocratic Leader/Chief (bound),Jury/Judge,Con...","Population numbers from Wikipedia, citing Dome...",5th - 11th century AD,"Europe, West",Europe,"1,000,001 - 10,000,000","Stasavage, David (2020), The Decline and Rise ...",NaN,NaN,Edited Feb 23 (can probably be expanded with s...,NaN,400,1100,NaN,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
18,G/wi,Band,"Deliberation,Consensus,Exit,Open political uni...","Bushmen band in the central Kalahari, hunter-g...",20th century - Present,"Africa, South, Botswana",Africa,"1,001 - 10,000","Silberbauer, G. Political process in G/wi band...",NaN,NaN,Edited Apr 23,NaN,1900,2000,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

## Time span

In [107]:
gov_df['Time span: Duration'] = gov_df['Time span: End'] - gov_df['Time span: Start']

/var/folders/48/y14p8x4x4nj59cpvfzzjdx200000gn/T/ipykernel_18009/3756383725.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  gov_df['Time span: Duration'] = gov_df['Time span: End'] - gov_df['Time span: Start']

# Write to CSV

### Check

In [108]:
gov_df.head()

,Name,Institutions,Mechanism,Notes,Time span,Geography,Continent,Size,Source,Metanotes,Heterogeneity,FC comments,expert check,Time span: Start,Time span: End,SCCS,is_SCCS,enforcement_mechanisms_include_tribunal_court_,decision_making_mechanisms_include_checks_and_balances,decision_making_mechanisms_include_rule_of_law,enforcement_mechanisms_include_reputational_risk,decision_making_mechanisms_include_confederacy,decision_making_mechanisms_include_consultation,decision_making_mechanisms_include_power_fluidity,enforcement_mechanisms_include_police,decision_making_mechanisms_include_coalition,enforcement_mechanisms_include_fines,decision_making_mechanisms_include_veto,decision_making_mechanisms_include_majority_voting,enforcement_mechanisms_include_jury_judge,decision_making_mechanisms_include_mandate,enforcement_mechanisms_include_paying_damages_compensation,decision_making_mechanisms_include_bureaucracy,decision_making_mechanisms_include_word_of_mouth,decision_making_mechanisms_include_assembly_local,decision_making_mechanisms_include_dual-sex_political_system,enforcement_mechanisms_include_civil_disobedience,decision_making_mechanisms_include_assembly_elite,access_mechanisms_include_enfranchisement,decision_making_mechanisms_include_alliance,decision_making_mechanisms_include_kingchief-as-figurehead,decision_making_mechanisms_include_group_voting,decision_making_mechanisms_include_plurality_voting,decision_making_mechanisms_include_vote_by_show_of_hands,decision_making_mechanisms_include_delegation,decision_making_mechanisms_include_board_committee,access_mechanisms_include_screening_process,access_mechanisms_include_divine_right,enforcement_mechanisms_include_negotiation,decision_making_mechanisms_include_magistrate_official,decision_making_mechanisms_include_council_local,enforcement_mechanisms_include_mediation,decision_making_mechanisms_include_lobbying,enforcement_mechanisms_include_capital_punishment,access_mechanisms_include_lottery_random_selection,enforcement_mechanisms_include_graduated_sanctions,decision_making_mechanisms_include_frequent_and_or_regular_meetings,decision_making_mechanisms_include_gathering,access_mechanisms_include_dreaming,enforcement_mechanisms_include_criticism_mocking_joking,access_mechanisms_include_meritocracy,decision_making_mechanisms_include_agenda_setting,access_mechanisms_include_matriarchy,access_mechanisms_include_payment_for_occupying_office,access_mechanisms_include_child_participation,decision_making_mechanisms_include_secret_ballot,access_mechanisms_include_gerontocracy,decision_making_mechanisms_include_temporary_position_of_power_term_limits,enforcement_mechanisms_include_destruction_of_property,access_mechanisms_include_patronage_for_office,decision_making_mechanisms_include_turnover_rotation,access_mechanisms_include_heredity,decision_making_mechanisms_include_autocratic_leader_chief_bound,decision_making_mechanisms_include_assembly_central,enforcement_mechanisms_include_self-help,decision_making_mechanisms_include_petition,enforcement_mechanisms_include_suspension_expulsion_ostracism_proscription,access_mechanisms_include_blood_relations,enforcement_mechanisms_include_monitoring,enforcement_mechanisms_include_corporal_punishment_violence_against_perpetrator,decision_making_mechanisms_include_balance_of_power,decision_making_mechanisms_include_council_central_,access_mechanisms_include_female_participation,decision_making_mechanisms_include_deliberation,enforcement_mechanisms_include_exit,enforcement_mechanisms_include_appeal,access_mechanisms_include_popularity_,decision_making_mechanisms_include_unanimity,enforcement_mechanisms_include_judicial_review,decision_making_mechanisms_include_oath,decision_making_mechanisms_include_supermajority,enforcement_mechanisms_include_seizing_of_property,enforcement_mechanisms_include_arbitration,decision_making_mechanisms_include_remunerated_position,enforcement_mechanisms_include_litigation,decision_making_mechanisms_include_representation,decision_making_mechanisms_include_quorum,decision_making_mechanisms_include_consent,access_mechanisms_include_co-optation,decision_making_mechanisms_include_constitution,access_mechanisms_include_induction_rite_ceremony,enforcement_mechanisms_include_scrutiny_of_officials,decision_making_mechanisms_include_president_consul_chief_executive,decision_making_mechanisms_include_public_meetings,access_mechanisms_include_age_boundaries,decision_making_mechanisms_include_vote_by_proxy,decision_making_mechanisms_include_voting,access_mechanisms_include_matrilineality,decision_making_mechanisms_include_consensus,decision_making_mechanisms_include_ratification_acclamation_only,access_mechanisms_include_election,access_mechanisms_include_life_appointment,access_mechanisms_include_property_requirement,decision_making_mechanisms_include_autocratic_leader_unbound,access_mechanisms_include_open_political_unit,enforcement_mechanisms_include_forced_labour,decision_making_mechanisms_include_leader_first_among_equals,"Size: 100 - 1,000","Size: 1,001 - 10,000","Size: 10,001 - 100,000","Size: 100,001 - 1,000,000","Size: 1,000,001 - 10,000,000","Size: 10,000,000+",Size: Unknown,"Geography: Europe, North","Geography: Asia, Southeast","Geography: Europe, West","Geography: Asia, Middle East","Geography: Asia, Southwest, Anatolia","Geography: Europe, South","Geography: North America, Central America","Geography: Asia, Middle East, Mesopotamia","Geography: Africa, North","Geography: Africa, Central","Geography: Asia, China","Geography: Europe, East","Geography: Africa, North","Geography: Africa, South, Botswana","Geography: Europe, Italy","Geography: Europe, South, Greece",Geography: North America,"Geography: Africa, West, Nigeria","Geography: Asia, Southeast","Geography: Africa, West, Mid-western Nigeria","Geography: Africa, West, Niger Delta","Geography: Asia, India (northeast)","Geography: Asia, Japan","Geography: Asia, North-eastern India",Geography: Africa South,"Geography: Europe South, Italy","Geography: Africa, North, Algeria","Geography: Asia, Central","Geography: Asia, Southwestern China","Geography: South America, Brazil","Geography: North America, Louisiana","Geography: Asia, Southeast, Bali","Geography: North America, Central America, Mexico","Geography: Asia, India","Geography: Asia, Middle East","Geography: Europe, South, Italy","Geography: South America, Patagonia","Geography: South America, Venezuela/Brazil","Geography: Oceania, New Caledonia","Geography: Oceania, New Zealand","Geography: Oceania, eastern Polynesia","Geography: Oceania, samoa","Geography: Oceania, Kiribati","Geography: Asia, South","Geography: Asia, East",Geography: Africa,"Geography: North America, Alaska","Geography: North America, Canada",Continent: Asia,Continent: Europe,Continent: North America,Continent: Africa,Continent: Oceania,Continent: South America,Continent: Antarctica,Time span: Duration
0,Aedui (Celtic Oppida),"Senatus,Elected magistrates,Assemblies","Election,Council (central) ,Assembly (central)...",There are many Celtic oppida throughout northe...,2nd-1st century BC,"Europe, North",Europe,"100,001 - 1,000,000","Collis, “Celtic” Oppida, in Hansen, A Comparat...",NaN,NaN,Edited March 23,NaN,-200,0,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,200
1,Akha,"Council of Elders,Village Founder-Leader (dzom...","Leader (first among equals),Gerontocracy,Blood...",see Institutions tab,20th century - Present,"Asia, Southeast",Asia,"10,001 - 100,000","Main: \nKammerer, Cornelia Ann (1985/86), Gate...",NaN,"Informal inclusion,Gender groups,Informal powe...",Edited May 23,NaN,1900,2023,NaN,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,123
2,Amalfi,"Prefetturii/ Conti/ Dogi,Sedile di congrega,Ta...","Election,Magistrate/official,Heredity,Constitu...","Camera, M, p. 29 (""La sua popolazione che nel ...",4th-12th century AD,"Europe, West",Europe,"10,001 - 100,000","Camera, M. Istoria della città e costiera di A...",NaN,NaN,Edited March 23 (could use more info on CGIs),NaN,300,1200,NaN,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,900
3,Arab nomads,"shaykh or sayyid,shura or mashwara","Consensus,Consultation,Autocratic Leader/Chief...",Nomadic Bedouin society governed by rulers sel...,"1st-7th century AD\n(start date is arbitrary, ...","Asia, Middle East",Asia,Unknown,"Stasavage, David (2020), The Decline and Rise ...",NaN,NaN,Edited Feb 23 (could use additional sources fo...,NaN,0,700,NaN,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,700
4,Assur,"King,Alum,Limmum,Scribe,City hall","President/Consul/Chief Executive,Assembly (cen...",Independent city-state. Constitutional monarch...,19th century BC\n(1920-1800 BC),"Asia, Southwest, Anatolia",Asia,"1,001 - 10,000","Larsen, M. T. The Old Assyrian City-State in H...",NaN,NaN,Edited Mar 23,Giacomo CHECKED,-1920,-1800,NaN,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,120

In [109]:
list(gov_df)

['Name',
 'Institutions',
 'Mechanism',
 'Notes',
 'Time span',
 'Geography',
 'Continent',
 'Size',
 'Source',
 'Metanotes',
 'Heterogeneity ',
 'FC comments',
 'expert check',
 'Time span: Start',
 'Time span: End',
 'SCCS',
 'is_SCCS',
 'enforcement_mechanisms_include_tribunal_court_',
 'decision_making_mechanisms_include_checks_and_balances',
 'decision_making_mechanisms_include_rule_of_law',
 'enforcement_mechanisms_include_reputational_risk',
 'decision_making_mechanisms_include_confederacy',
 'decision_making_mechanisms_include_consultation',
 'decision_making_mechanisms_include_power_fluidity',
 'enforcement_mechanisms_include_police',
 'decision_making_mechanisms_include_coalition',
 'enforcement_mechanisms_include_fines',
 'decision_making_mechanisms_include_veto',
 'decision_making_mechanisms_include_majority_voting',
 'enforcement_mechanisms_include_jury_judge',
 'decision_making_mechanisms_include_mandate',
 'enforcement_mechanisms_include_paying_damages_compensation',
 'decision_making_mechanisms_include_bureaucracy',
 'decision_making_mechanisms_include_word_of_mouth',
 'decision_making_mechanisms_include_assembly_local',
 'decision_making_mechanisms_include_dual-sex_political_system',
 'enforcement_mechanisms_include_civil_disobedience',
 'decision_making_mechanisms_include_assembly_elite',
 'access_mechanisms_include_enfranchisement',
 'decision_making_mechanisms_include_alliance',
 'decision_making_mechanisms_include_kingchief-as-figurehead',
 'decision_making_mechanisms_include_group_voting',
 'decision_making_mechanisms_include_plurality_voting',
 'decision_making_mechanisms_include_vote_by_show_of_hands',
 'decision_making_mechanisms_include_delegation',
 'decision_making_mechanisms_include_board_committee',
 'access_mechanisms_include_screening_process',
 'access_mechanisms_include_divine_right',
 'enforcement_mechanisms_include_negotiation',
 'decision_making_mechanisms_include_magistrate_official',
 'decision_making_mechanisms_include_council_local',
 'enforcement_mechanisms_include_mediation',
 'decision_making_mechanisms_include_lobbying',
 'enforcement_mechanisms_include_capital_punishment',
 'access_mechanisms_include_lottery_random_selection',
 'enforcement_mechanisms_include_graduated_sanctions',
 'decision_making_mechanisms_include_frequent_and_or_regular_meetings',
 'decision_making_mechanisms_include_gathering',
 'access_mechanisms_include_dreaming',
 'enforcement_mechanisms_include_criticism_mocking_joking',
 'access_mechanisms_include_meritocracy',
 'decision_making_mechanisms_include_agenda_setting',
 'access_mechanisms_include_matriarchy',
 'access_mechanisms_include_payment_for_occupying_office',
 'access_mechanisms_include_child_participation',
 'decision_making_mechanisms_include_secret_ballot',
 'access_mechanisms_include_gerontocracy',
 'decision_making_mechanisms_include_temporary_position_of_power_term_limits',
 'enforcement_mechanisms_include_destruction_of_property',
 'access_mechanisms_include_patronage_for_office',
 'decision_making_mechanisms_include_turnover_rotation',
 'access_mechanisms_include_heredity',
 'decision_making_mechanisms_include_autocratic_leader_chief_bound',
 'decision_making_mechanisms_include_assembly_central',
 'enforcement_mechanisms_include_self-help',
 'decision_making_mechanisms_include_petition',
 'enforcement_mechanisms_include_suspension_expulsion_ostracism_proscription',
 'access_mechanisms_include_blood_relations',
 'enforcement_mechanisms_include_monitoring',
 'enforcement_mechanisms_include_corporal_punishment_violence_against_perpetrator',
 'decision_making_mechanisms_include_balance_of_power',
 'decision_making_mechanisms_include_council_central_',
 'access_mechanisms_include_female_participation',
 'decision_making_mechanisms_include_deliberation',
 'enforcement_mechanisms_include_exit',
 'enforcement_mechanisms_include_appeal',
 'access_mechanisms_include_popularity_',
 'decision_making_mechanisms_include_unanimity',
 'enforcement_mechanisms_include_judicial_review',
 'decision_making_mechanisms_include_oath',
 'decision_making_mechanisms_include_supermajority',
 'enforcement_mechanisms_include_seizing_of_property',
 'enforcement_mechanisms_include_arbitration',
 'decision_making_mechanisms_include_remunerated_position',
 'enforcement_mechanisms_include_litigation',
 'decision_making_mechanisms_include_representation',
 'decision_making_mechanisms_include_quorum',
 'decision_making_mechanisms_include_consent',
 'access_mechanisms_include_co-optation',
 'decision_making_mechanisms_include_constitution',
 'access_mechanisms_include_induction_rite_ceremony',
 'enforcement_mechanisms_include_scrutiny_of_officials',
 'decision_making_mechanisms_include_president_consul_chief_executive',
 'decision_making_mechanisms_include_public_meetings',
 'access_mechanisms_include_age_boundaries',
 'decision_making_mechanisms_include_vote_by_proxy',
 'decision_making_mechanisms_include_voting',
 'access_mechanisms_include_matrilineality',
 'decision_making_mechanisms_include_consensus',
 'decision_making_mechanisms_include_ratification_acclamation_only',
 'access_mechanisms_include_election',
 'access_mechanisms_include_life_appointment',
 'access_mechanisms_include_property_requirement',
 'decision_making_mechanisms_include_autocratic_leader_unbound',
 'access_mechanisms_include_open_political_unit',
 'enforcement_mechanisms_include_forced_labour',
 'decision_making_mechanisms_include_leader_first_among_equals',
 'Size: 100 - 1,000',
 'Size: 1,001 - 10,000',
 'Size: 10,001 - 100,000',
 'Size: 100,001 - 1,000,000',
 'Size: 1,000,001 - 10,000,000',
 'Size: 10,000,000+',
 'Size: Unknown',
 'Geography: Europe, North',
 'Geography: Asia, Southeast ',
 'Geography: Europe, West',
 'Geography: Asia, Middle East',
 'Geography: Asia, Southwest, Anatolia',
 'Geography: Europe, South',
 'Geography: North America, Central America',
 'Geography: Asia, Middle East, Mesopotamia',
 'Geography: Africa, North ',
 'Geography: Africa, Central',
 'Geography: Asia, China',
 'Geography: Europe, East',
 'Geography: Africa, North',
 'Geography: Africa, South, Botswana',
 'Geography: Europe, Italy',
 'Geography: Europe, South, Greece',
 'Geography: North America',
 'Geography: Africa, West, Nigeria',
 'Geography: Asia, Southeast',
 'Geography: Africa, West, Mid-western Nigeria',
 'Geography: Africa, West, Niger Delta',
 'Geography: Asia, India (northeast)',
 'Geography: Asia, Japan',
 'Geography: Asia, North-eastern India',
 'Geography: Africa South',
 'Geography: Europe South, Italy',
 'Geography: Africa, North, Algeria',
 'Geography: Asia, Central',
 'Geography: Asia, Southwestern China',
 'Geography: South America, Brazil',
 'Geography: North America, Louisiana',
 'Geography: Asia, Southeast, Bali',
 'Geography: North America, Central America, Mexico',
 'Geography: Asia, India',
 'Geography: Asia, Middle East ',
 'Geography: Europe, South, Italy',
 'Geography: South America, Patagonia',
 'Geography: South America, Venezuela/Brazil',
 'Geography: Oceania, New Caledonia',
 'Geography: Oceania, New Zealand',
 'Geography: Oceania, eastern Polynesia',
 'Geography: Oceania, samoa',
 'Geography: Oceania, Kiribati',
 'Geography: Asia, South',
 'Geography: Asia, East',
 'Geography: Africa',
 'Geography: North America, Alaska',
 'Geography: North America, Canada',
 'Continent: Asia',
 'Continent: Europe',
 'Continent: North America',
 'Continent: Africa',
 'Continent: Oceania',
 'Continent: South America',
 'Continent: Antarctica',
 'Time span: Duration']

In [110]:
gov_df.select_dtypes(include=np.number).sum().sort_values()

Continent: Antarctica                                                                   0
decision_making_mechanisms_include_lobbying                                             1
Geography: Africa, West, Nigeria                                                        1
Geography: South America, Patagonia                                                     1
decision_making_mechanisms_include_petition                                             1
decision_making_mechanisms_include_group_voting                                         1
Geography: Africa, West, Mid-western Nigeria                                            1
Geography: Africa, West, Niger Delta                                                    1
Geography: Asia, Middle East                                                            1
Geography: Asia, India                                                                  1
Geography: Asia, Japan                                                                  1
Geography: Asia, North-eastern India                                                    1
Geography: North America, Central America, Mexico                                       1
Geography: Asia, Southeast, Bali                                                        1
Geography: North America, Louisiana                                                     1
Geography: Africa South                                                                 1
Geography: Asia, Southwest, Anatolia                                                    1
Geography: Asia, Middle East, Mesopotamia                                               1
Geography: Europe South, Italy                                                          1
Geography: Asia, Southwestern China                                                     1
Geography: South America, Venezuela/Brazil                                              1
Geography: Asia, Central                                                                1
enforcement_mechanisms_include_civil_disobedience                                       1
Geography: Oceania, New Caledonia                                                       1
Geography: North America, Alaska                                                        1
Geography: Africa, Central                                                              1
Geography: Asia, China                                                                  1
Geography: Africa, North                                                                1
Geography: Asia, East                                                                   1
decision_making_mechanisms_include_power_fluidity                                       1
Geography: Oceania, Kiribati                                                            1
decision_making_mechanisms_include_coalition                                            1
Geography: Africa, North                                                                1
Geography: Oceania, eastern Polynesia                                                   1
Geography: Oceania, New Zealand                                                         1
decision_making_mechanisms_include_mandate                                              1
Geography: Africa, South, Botswana                                                      1
Geography: Europe, South                                                                1
Geography: Oceania, samoa                                                               1
Geography: Africa, North, Algeria                                                       1
enforcement_mechanisms_include_destruction_of_property                                  2
Geography: Europe, South, Greece                                                        2
enforcement_mechanisms_include_monitoring                                               2
enforcement_mechanisms_include_judicial_review                                          2
decision_making_mechanisms_include_oath                                                 2
decision_making_mechanisms_include_quorum                                               2
enforcement_mechanisms_include_graduated_sanctions                                      2
access_mechanisms_include_enfranchisement                                               2
decision_making_mechanisms_include_bureaucracy                                          2
decision_making_mechanisms_include_plurality_voting                                     2
Geography: Asia, Southeast                                                              2
access_mechanisms_include_screening_process                                             2
Geography: Asia, South                                                                  2
decision_making_mechanisms_include_vote_by_proxy                                        2
Geography: North America, Canada                                                        2
enforcement_mechanisms_include_forced_labour                                            2
decision_making_mechanisms_include_supermajority                                        2
Geography: South America, Brazil                                                        2
decision_making_mechanisms_include_rule_of_law                                          2
decision_making_mechanisms_include_word_of_mouth                                        2
enforcement_mechanisms_include_appeal                                                   3
Geography: Europe, East                                                                 3
Geography: Europe, North                                                                3
enforcement_mechanisms_include_paying_damages_compensation                              3
Geography: Europe, Italy                                                                3
Geography: Europe, South, Italy                                                         3
Geography: Asia, Southeast                                                              3
decision_making_mechanisms_include_vote_by_show_of_hands                                3
Geography: Asia, India (northeast)                                                      3
decision_making_mechanisms_include_turnover_rotation                                    3
access_mechanisms_include_patronage_for_office                                          3
enforcement_mechanisms_include_scrutiny_of_officials                                    3
enforcement_mechanisms_include_negotiation                                              3
decision_making_mechanisms_include_secret_ballot                                        3
access_mechanisms_include_co-optation                                                   3
access_mechanisms_include_payment_for_occupying_office                                  3
access_mechanisms_include_dreaming                                                      3
enforcement_mechanisms_include_seizing_of_property                                      3
Geography: Asia, Middle East                                                            4
Size: 10,000,000+                                                                       4
Geography: North America, Central America                                               4
decision_making_mechanisms_include_agenda_setting                                       4
enforcement_mechanisms_include_exit                                                     4
decision_making_mechanisms_include_balance_of_power                                     4
access_mechanisms_include_child_participation                                           4
access_mechanisms_include_lottery_random_selection                                      4
access_mechanisms_include_divine_right                                                  4
decision_making_mechanisms_include_dual-sex_political_system                            4
decision_making_mechanisms_include_veto                                                 4
enforcement_mechanisms_include_reputational_risk                                        4
Continent: South America                                                                4
enforcement_mechanisms_include_litigation                                               4
decision_making_mechanisms_include_autocratic_leader_unbound                            5
Geography: Africa                                                                       5
Size: 100 - 1,000                                                                       5
access_mechanisms_include_property_requirement                                          5
Continent: Oceania                                                                      5
decision_making_mechanisms_include_alliance                                             5
enforcement_mechanisms_include_fines                                                    5
access_mechanisms_include_induction_rite_ceremony                                       5
Geography: Europe, West                                                                 6
decision_making_mechanisms_include_ratification_acclamation_only                        6
enforcement_mechanisms_include_self-help                                                6
access_mechanisms_include_open_political_unit                                           6
enforcement_mechanisms_include_capital_punishment                                       6
enforcement_mechanisms_include_criticism_mocking_joking                                 6
Size: 1,000,001 - 10,000,000                                                            6
Size: Unknown                                                                           7
access_mechanisms_include_matriarchy                                                    7
decision_making_mechanisms_include_unanimity                                            7
access_mechanisms_include_popularity_                                                   7
enforcement_mechanisms_include_police                                                   7
access_mechanisms_include_age_boundaries                                                7
decision_making_mechanisms_include_constitution                                         7
decision_making_mechanisms_include_majority_voting                                      8
decision_making_mechanisms_include_assembly_elite                                       8
decision_making_mechanisms_include_board_committee                                      8
decision_making_mechanisms_include_delegation                                           8
access_mechanisms_include_matrilineality                                                8
enforcement_mechanisms_include_mediation                                                8
enforcement_mechanisms_include_suspension_expulsion_ostracism_proscription              8
enforcement_mechanisms_include_arbitration                                              9
decision_making_mechanisms_include_voting                                               9
decision_making_mechanisms_include_leader_first_among_equals                            9
decision_making_mechanisms_include_checks_and_balances                                  9
decision_making_mechanisms_include_confederacy                                          9
enforcement_mechanisms_include_jury_judge                                              10
decision_making_mechanisms_include_kingchief-as-figurehead                             10
access_mechanisms_include_life_appointment                                             10
enforcement_mechanisms_include_corporal_punishment_violence_against_perpetrator        10
Size: 100,001 - 1,000,000                                                              10
decision_making_mechanisms_include_remunerated_position                                10
decision_making_mechanisms_include_consent                                             10
decision_making_mechanisms_include_gathering                                           12
Geography: North America                                                               12
decision_making_mechanisms_include_president_consul_chief_executive                    12
decision_making_mechanisms_include_assembly_local                                      13
access_mechanisms_include_blood_relations                                              14
Continent: Africa                                                                      14
decision_making_mechanisms_include_consultation                                        16
decision_making_mechanisms_include_frequent_and_or_regular_meetings                    18
decision_making_mechanisms_include_public_meetings                                     18
decision_making_mechanisms_include_temporary_position_of_power_term_limits             21
Continent: North America                                                               21
Continent: Europe                                                                      22
Size: 1,001 - 10,000                                                                   22
access_mechanisms_include_female_participation                                         22
enforcement_mechanisms_include_tribunal_court_                                         23
decision_making_mechanisms_include_representation                                      24
Continent: Asia                                                                        25
decision_making_mechanisms_include_consensus                                           25
decision_making_mechanisms_include_assembly_central                                    27
decision_making_mechanisms_include_council_local                                       28
access_mechanisms_include_election                                                     28
decision_making_mechanisms_include_deliberation                                        34
is_SCCS                                                                                34
access_mechanisms_include_gerontocracy                                                 36
Size: 10,001 - 100,000                                                                 37
decision_making_mechanisms_include_autocratic_leader_chief_bound                       38
access_mechanisms_include_meritocracy                                                  40
access_mechanisms_include_heredity                                                     40
decision_making_mechanisms_include_council_central_                                    53
decision_making_mechanisms_include_magistrate_official                                 61
Time span: Duration                                                                 31471
Time span: Start                                                                    77148
Time span: End                                                                     108619
dtype: int64

In [111]:
# Write prepped dataset to csv
gov_df.to_csv('../data/' + DATA_VERSION + '/communities_data_prepped.csv', index=False)